In [1]:
pip install awswrangler

Collecting awswrangler
  Using cached awswrangler-3.16.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: boto3<2,>=1.20.32 in /opt/conda/lib/python3.11/site-packages (from awswrangler) (1.36.3)
Requirement already satisfied: botocore<2,>=1.23.32 in /opt/conda/lib/python3.11/site-packages (from awswrangler) (1.36.3)
Requirement already satisfied: numpy<3.0,>=1.26 in /opt/conda/lib/python3.11/site-packages (from awswrangler) (1.26.4)
Requirement already satisfied: packaging<27.0,>=21.1 in /opt/conda/lib/python3.11/site-packages (from awswrangler) (24.2)
Requirement already satisfied: pandas<4.0.0,>=1.2.0 in /opt/conda/lib/python3.11/site-packages (from awswrangler) (2.2.3)
Requirement already satisfied: pyarrow<24.0.0,>=8.0.0 in /opt/conda/lib/python3.11/site-packages (from awswrangler) (17.0.0)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /opt/conda/lib/python3.11/site-packages (from awswrangler) (4.12.2)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.11/site-packages (from boto3<2,>=1.20.32->awswrangler) (1.0.1)
Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /opt/conda/lib/python3.11/site-packages (from boto3<2,>=1.20.32->awswrangler) (0.11.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.11/site-packages (from botocore<2,>=1.23.32->awswrangler) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.11/site-packages (from botocore<2,>=1.23.32->awswrangler) (1.26.19)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas<4.0.0,>=1.2.0->awswrangler) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas<4.0.0,>=1.2.0->awswrangler) (2025.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2,>=1.23.32->awswrangler) (1.17.0)
Using cached awswrangler-3.16.0-py3-none-any.whl (381 kB)
Installing collected packages: awswrangler
Successfully installed awswrangler-3.16.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install awswrangler[openpyxl]

Requirement already satisfied: awswrangler[openpyxl] in /opt/conda/lib/python3.11/site-packages (3.16.0)
Requirement already satisfied: boto3<2,>=1.20.32 in /opt/conda/lib/python3.11/site-packages (from awswrangler[openpyxl]) (1.36.3)
Requirement already satisfied: botocore<2,>=1.23.32 in /opt/conda/lib/python3.11/site-packages (from awswrangler[openpyxl]) (1.36.3)
Requirement already satisfied: numpy<3.0,>=1.26 in /opt/conda/lib/python3.11/site-packages (from awswrangler[openpyxl]) (1.26.4)
Requirement already satisfied: packaging<27.0,>=21.1 in /opt/conda/lib/python3.11/site-packages (from awswrangler[openpyxl]) (24.2)
Requirement already satisfied: pandas<4.0.0,>=1.2.0 in /opt/conda/lib/python3.11/site-packages (from awswrangler[openpyxl]) (2.2.3)
Requirement already satisfied: pyarrow<24.0.0,>=8.0.0 in /opt/conda/lib/python3.11/site-packages (from awswrangler[openpyxl]) (17.0.0)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /opt/conda/lib/python3.11/site-packages (from awswrangler[openpyxl]) (4.12.2)
Collecting openpyxl<4,>=3.0.0 (from awswrangler[openpyxl])
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.11/site-packages (from boto3<2,>=1.20.32->awswrangler[openpyxl]) (1.0.1)
Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /opt/conda/lib/python3.11/site-packages (from boto3<2,>=1.20.32->awswrangler[openpyxl]) (0.11.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.11/site-packages (from botocore<2,>=1.23.32->awswrangler[openpyxl]) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.11/site-packages (from botocore<2,>=1.23.32->awswrangler[openpyxl]) (1.26.19)
Collecting et-xmlfile (from openpyxl<4,>=3.0.0->awswrangler[openpyxl])
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas<4.0.0,>=1.2.0->awswrangler[openpyxl]) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas<4.0.0,>=1.2.0->awswrangler[openpyxl]) (2025.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2,>=1.23.32->awswrangler[openpyxl]) (1.17.0)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install s3fs

Requirement already satisfied: s3fs in /opt/conda/lib/python3.11/site-packages (2024.10.0)
Requirement already satisfied: aiobotocore<3.0.0,>=2.5.4 in /opt/conda/lib/python3.11/site-packages (from s3fs) (2.19.0)
Requirement already satisfied: fsspec==2024.10.0.* in /opt/conda/lib/python3.11/site-packages (from s3fs) (2024.10.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.11/site-packages (from s3fs) (3.9.5)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (0.12.0)
Requirement already satisfied: botocore<1.36.4,>=1.36.0 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.36.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (2.9.0.post0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.0.1)
Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (6.1.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.26.19)
Requirement already satisfied: wrapt<2.0.0,>=1.10.10 in /opt/conda/lib/python3.11/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.17.2)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.5.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.18.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil<3.0.0,>=2.1->aiobotocore<3.0.0,>=2.5.4->s3fs) (1.17.0)
Requirement already satisfied: idna>=2.0 in /opt/conda/lib/python3.11/site-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (3.10)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.11/site-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (0.2.1)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install fsspec

Requirement already satisfied: fsspec in /opt/conda/lib/python3.11/site-packages (2024.10.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install openpyxl

Requirement already satisfied: openpyxl in /opt/conda/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/conda/lib/python3.11/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

## Tata 1Mg

In [6]:
import pandas as pd
import numpy as np
import gc
import awswrangler as wr

In [7]:
import boto3
s3 = boto3.resource('s3')

## Bucket to use
bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

## List objects within a given prefix
filenames_1mg = [obj.key for obj in bucket.objects.filter(Delimiter=',', Prefix='raw/From 2026/1MG')]

In [8]:
filenames_1mg = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_1mg]

In [9]:
filenames_1mg

['s3://abt-aa-india-202005001-nonprod/raw/From 2026/1MG/',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/1MG/Abbott-February-26-Sales_Tata 1mg.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/1MG/Abbott-January-26-Sales_Tata 1mg.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/1MG/Abbott-March-26-Sales_Tata 1mg.xlsx']

In [10]:
filenames_1mg = filenames_1mg[1:]

In [11]:
cols_to_keep = ["month","customer_pincode","customer_city","sku_id","units_sold", "gmv_list_price","sku_name"]

In [12]:
    dfs_xlsx = []
    dfs_xlsb = []
    for file in filenames_1mg[0:]:
        if "xlsx" in file:
            try:
                df_inter = wr.s3.read_excel(file)
                df_inter = df_inter[cols_to_keep]
                dfs_xlsb.append(df_inter)
            except:
                print(file)
        if "xlsx" in file:
            try:
                df_inter = wr.s3.read_excel(file)
                df_inter = df_inter[cols_to_keep]
                dfs_xlsx.append(df_inter)
            except Exception as e:
                print(e)

In [13]:
gc.collect()

63890

In [14]:
data_1mg = pd.concat(dfs_xlsx)

In [15]:
data_1mg

,month,customer_pincode,customer_city,sku_id,units_sold,gmv_list_price,sku_name
0,"February, 2026",411014,pune,800528,2,623.90,CremaGel-L Rectal Gel
1,"February, 2026",560037,bangalore,822193,30,23464.80,"New Follihair Tablet | Strengthens, Stimulate..."
2,"February, 2026",560061,bangalore,351840,2,379.40,THYronorm 12.5mcg Tablet
3,"February, 2026",226003,lucknow,184375,3,1305.03,Selsun Suspension Anti Dandruff Shampoo | Hair...
4,"February, 2026",456010,ujjain,357013,1,132.02,THYronorm 50mcg Tablet
...,...,...,...,...,...,...,...
60750,"March, 2026",248013,dehradun,323191,1,432.48,Arachitol Nano Bottle 60K IU Vitamin D3 Oral S...
60751,"March, 2026",400604,thane,113478,1,517.40,Acitrom 2 Tablet
60752,"March, 2026",534004,west godavari,690024,3,844.59,Tyza Tablet
60753,"March, 2026",110094,new delhi,323068,1,30.10,"Digene Antacid Antigas Tablet | For Acidity, G..."
60754,"March, 2026",560003,bangalore,372197,1,217.90,THYronorm 150mcg Tablet

In [16]:
data_1mg['month']= pd.to_datetime(data_1mg['month'])

/tmp/ipykernel_458/2284167782.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data_1mg['month']= pd.to_datetime(data_1mg['month'])

In [17]:
data_1mg['month'].unique()

<DatetimeArray>
['2026-02-01 00:00:00', '2026-01-01 00:00:00', '2026-03-01 00:00:00']
Length: 3, dtype: datetime64[ns]

In [18]:
sum(data_1mg.loc[(data_1mg['month'] == '2026-03-01'), "gmv_list_price"])

71819972.06910276

In [19]:
data_1mg.rename(columns={data_1mg.columns[0]:'month',data_1mg.columns[1]:'pincode',data_1mg.columns[2]:'city',data_1mg.columns[3]:'product_code',data_1mg.columns[4]:'units_sold',data_1mg.columns[5]:'revenue',data_1mg.columns[6]:'sku_name'},inplace =True)

In [20]:
data_1mg

,month,pincode,city,product_code,units_sold,revenue,sku_name
0,2026-02-01,411014,pune,800528,2,623.90,CremaGel-L Rectal Gel
1,2026-02-01,560037,bangalore,822193,30,23464.80,"New Follihair Tablet | Strengthens, Stimulate..."
2,2026-02-01,560061,bangalore,351840,2,379.40,THYronorm 12.5mcg Tablet
3,2026-02-01,226003,lucknow,184375,3,1305.03,Selsun Suspension Anti Dandruff Shampoo | Hair...
4,2026-02-01,456010,ujjain,357013,1,132.02,THYronorm 50mcg Tablet
...,...,...,...,...,...,...,...
60750,2026-03-01,248013,dehradun,323191,1,432.48,Arachitol Nano Bottle 60K IU Vitamin D3 Oral S...
60751,2026-03-01,400604,thane,113478,1,517.40,Acitrom 2 Tablet
60752,2026-03-01,534004,west godavari,690024,3,844.59,Tyza Tablet
60753,2026-03-01,110094,new delhi,323068,1,30.10,"Digene Antacid Antigas Tablet | For Acidity, G..."
60754,2026-03-01,560003,bangalore,372197,1,217.90,THYronorm 150mcg Tablet

In [21]:
data_1mg.groupby('month')['revenue'].sum()

month
2026-01-01    6.921402e+07
2026-02-01    6.328327e+07
2026-03-01    7.181997e+07
Name: revenue, dtype: float64

## Medplus

In [35]:
import boto3
s3 = boto3.resource('s3')

## Bucket to use
bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

## List objects within a given prefix
filenames_medplus = [obj.key for obj in bucket.objects.filter(Prefix='raw/From 2026/Medplus')]

In [36]:
filenames_medplus = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_medplus]

In [37]:
filenames_medplus

['s3://abt-aa-india-202005001-nonprod/raw/From 2026/Medplus/',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Medplus/Medplus Offtake ABBOTT_PINCODE_Feb2026(Jan Data Copy).xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Medplus/Medplus Offtake ABBOTT_PINCODE_Jan2026.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Medplus/Medplus Offtake ABBOTT_PINCODE_Mar2026(Jan Data Copy).xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Medplus/YTD_Medplus/',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Medplus/YTD_Medplus/YTD_medplus_v0.pickle']

In [38]:
gc.collect()

5247

In [39]:
#Reading YTD pickle file
YTD_medplus=pd.read_pickle('s3://abt-aa-india-202005001-nonprod/raw/From 2026/Medplus/YTD_Medplus/YTD_medplus_v0.pickle')

In [40]:
filenames_medplus[3]

's3://abt-aa-india-202005001-nonprod/raw/From 2026/Medplus/Medplus Offtake ABBOTT_PINCODE_Mar2026(Jan Data Copy).xlsx'

In [51]:
#Reading latest medplus file
Latest_medplus=wr.s3.read_excel(filenames_medplus[3],sheet_name = "Pincode_Product_Summary")
cols_to_keep = ["Month","Pin Code","City","ProductID","ABBOTT Sales (Volume)","ABBOTT Sales (Value)","ProductName"]
Latest_medplus = Latest_medplus[cols_to_keep]
Latest_medplus['month'] = pd.to_datetime("01" + Latest_medplus['Month'] , format = "%d%b%Y")

In [52]:
YTD_medplus['month'].unique()

<DatetimeArray>
['2026-02-01 00:00:00', '2026-01-01 00:00:00']
Length: 2, dtype: datetime64[ns]

In [53]:
Latest_medplus.drop(["Month"], axis = 1, inplace = True)

In [54]:
Latest_medplus.columns

Index(['Pin Code', 'City', 'ProductID', 'ABBOTT Sales (Volume)',
       'ABBOTT Sales (Value)', 'ProductName', 'month'],
      dtype='object')

In [55]:
Latest_medplus.rename(columns={Latest_medplus.columns[0]: "pincode",Latest_medplus.columns[1]: "city",Latest_medplus.columns[2]: "product_code",Latest_medplus.columns[3]: "units_sold",Latest_medplus.columns[4]: "revenue",Latest_medplus.columns[5]:'sku_name',Latest_medplus.columns[6]: "month"}, inplace = True)
Latest_medplus = Latest_medplus[['month', 'pincode', 'city', 'product_code', 'units_sold', 'revenue','sku_name']]

In [56]:
Latest_medplus.columns

Index(['month', 'pincode', 'city', 'product_code', 'units_sold', 'revenue',
       'sku_name'],
      dtype='object')

In [57]:
Latest_medplus['month'].unique()

<DatetimeArray>
['2026-03-01 00:00:00']
Length: 1, dtype: datetime64[ns]

In [58]:
#data_medplus = pd.concat([YTD_medplus,Latest_medplus],axis=0)

In [59]:
data_medplus=pd.concat([Latest_medplus, YTD_medplus], axis = 0)

In [60]:
#data_medplus=Latest_medplus

In [61]:
data_medplus.head()

,month,pincode,city,product_code,units_sold,revenue,sku_name
0,2026-03-01,110018,NEWDELHI,ABOC0001,0,0.0,ABOCAL 500MG TAB
1,2026-03-01,122001,GURGAON,ABOC0001,0,0.0,ABOCAL 500MG TAB
2,2026-03-01,201307,NOIDA,ABOC0001,0,0.0,ABOCAL 500MG TAB
3,2026-03-01,400016,MUMBAI,ABOC0001,0,0.0,ABOCAL 500MG TAB
4,2026-03-01,400022,MUMBAI,ABOC0001,0,0.0,ABOCAL 500MG TAB

In [62]:
#data_medplus.drop(["Product name"], axis = 1, inplace = True)

In [63]:
data_medplus['month'].unique()

<DatetimeArray>
['2026-03-01 00:00:00', '2026-02-01 00:00:00', '2026-01-01 00:00:00']
Length: 3, dtype: datetime64[ns]

In [64]:
data_medplus['revenue'] = data_medplus['revenue'].astype(int)

In [65]:
sum(data_medplus.loc[(data_medplus['month']=='2026-03-01'),'revenue'])

153473589

In [66]:
data_medplus.dtypes

month           datetime64[ns]
pincode                  int64
city                    object
product_code            object
units_sold               int64
revenue                  int64
sku_name                object
dtype: object

In [67]:
data_medplus.groupby('month')['revenue'].sum()

month
2026-01-01    153473589
2026-02-01    153473589
2026-03-01    153473589
Name: revenue, dtype: int64

In [68]:
#Saving YTD medplus file
data_medplus.to_pickle('s3://abt-aa-india-202005001-nonprod/raw/From 2026/Medplus/YTD_Medplus/YTD_medplus_v0.pickle')

In [69]:
gc.collect()

3133

In [70]:
#data_medplus = pd.concat(dfs_xlsx)

## Flipkart Health Plus

In [71]:
import boto3
s3 = boto3.resource('s3')

## Bucket to use
bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

## List objects within a given prefix|
filenames_sasta = [obj.key for obj in bucket.objects.filter(Prefix='raw/From 2026/Sasta Sundar')]

In [72]:
filenames_sasta = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_sasta]

In [73]:
filenames_sasta

['s3://abt-aa-india-202005001-nonprod/raw/From 2026/Sasta Sundar/',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Sasta Sundar/ABBOTT_AREA_REPORT_Feb 2026_SastaSundar.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Sasta Sundar/ABBOTT_AREA_REPORT_Jan 2026_SastaSundar.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Sasta Sundar/ABBOTT_AREA_REPORT_Mar 2026_SastaSundar.xlsx']

In [74]:
filenames_sasta = filenames_sasta[1:]

In [75]:
gc.collect()

2114

In [76]:
cols_to_keep = ["PinCode","City","SourceProductId","SaleQty","GMV","ProductName"]
month_list = ["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"]

In [77]:
dfs_xlsx = []
dfs_xlsb = []
for file in filenames_sasta[0:]:
    if "xlsb" in file:
        try:
            df_inter = wr.s3.read_excel(file, sheet_name=  0)
            df_inter = df_inter[cols_to_keep]
            month_sasta = [x.upper() for x in month_list if x + " 2026" in file.lower()]
            df_inter['month'] = month_sasta[0]
            df_inter['month'] = pd.to_datetime("01" + df_inter['month'] + "2026", format = "%d%b%Y")
            dfs_xlsx.append(df_inter)
        except:
            print(file)
    if "xlsx" in file:
        try:
            df_inter = wr.s3.read_excel(file, sheet_name = 0)
            df_inter = df_inter[cols_to_keep]
            month_sasta = [x.upper() for x in month_list if x + " 2026" in file.lower()]
            df_inter['month'] = month_sasta[0]
            df_inter['month'] = pd.to_datetime("01" + df_inter['month'] + "2026", format = "%d%b%Y")
            dfs_xlsx.append(df_inter)
        except Exception as e:
            print(e)

In [78]:
gc.collect()

62697

In [79]:
data_sasta = pd.concat(dfs_xlsx)

In [80]:
data_sasta.rename(columns={data_sasta.columns[0]: "pincode",data_sasta.columns[1]: "city",data_sasta.columns[2]: "product_code",data_sasta.columns[3]: "units_sold",data_sasta.columns[4]: "revenue",data_sasta.columns[6]: "month",data_sasta.columns[5]:"sku_name"  }, inplace = True)

In [81]:
data_sasta = data_sasta[['month', 'pincode', 'city', 'product_code', 'units_sold', 'revenue','sku_name']]

In [82]:
data_sasta

,month,pincode,city,product_code,units_sold,revenue,sku_name
0,2026-02-01,110037,Delhi,10000009,1,330.34,Acitrom 1 mg Tablet (30 Tab)
1,2026-02-01,110040,Delhi,10000009,2,660.68,Acitrom 1 mg Tablet (30 Tab)
2,2026-02-01,110041,Delhi,10000009,1,330.34,Acitrom 1 mg Tablet (30 Tab)
3,2026-02-01,110043,Delhi,10000009,3,991.02,Acitrom 1 mg Tablet (30 Tab)
4,2026-02-01,110044,Delhi,10000009,2,660.68,Acitrom 1 mg Tablet (30 Tab)
...,...,...,...,...,...,...,...
60031,2026-03-01,741247,Nadia,10163082,1,2688.00,Influvac Tetra (Surface Antigen) 2026 Vaccine ...
60032,2026-03-01,721305,Kharagpur,10163082,1,2688.00,Influvac Tetra (Surface Antigen) 2026 Vaccine ...
60033,2026-03-01,712701,Hooghly,10163082,1,2688.00,Influvac Tetra (Surface Antigen) 2026 Vaccine ...
60034,2026-03-01,743337,South 24 Parganas,10163082,2,5376.00,Influvac Tetra (Surface Antigen) 2026 Vaccine ...
60035,2026-03-01,743331,South 24 Parganas,10163109,1,1345.00,Pediasure Vanilla Flavour Powder Refill (Rs. 2...

In [83]:
data_sasta.dtypes

month           datetime64[ns]
pincode                  int64
city                    object
product_code             int64
units_sold               int64
revenue                float64
sku_name                object
dtype: object

In [84]:
data_sasta.dtypes

month           datetime64[ns]
pincode                  int64
city                    object
product_code             int64
units_sold               int64
revenue                float64
sku_name                object
dtype: object

In [85]:
data_sasta.groupby('month')[['units_sold','revenue']].sum()

            units_sold      revenue
month
2026-01-01      287643  64556734.40
2026-02-01      298056  62282869.41
2026-03-01      309257  52817222.26

## Udaan (Removed from program)

In [75]:
# import boto3
# s3 = boto3.resource('s3')

# ## Bucket to use
# bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

# ## List objects within a given prefix
# filenames_udaan = [obj.key for obj in bucket.objects.filter(Prefix='raw/From 2025/Udaan')]

In [76]:
# filenames_udaan = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_udaan]

In [77]:
# filenames_udaan = filenames_udaan[1:]

In [78]:
# gc.collect()

2108

In [79]:
# cols_to_keep = ["PINCODE","CITY NAME","ITEM_CODE as per yours(PID)","Qty","Value","PROD_DSCR"]

In [80]:
# dfs_xlsx = []
# dfs_xlsb = []
# for file in filenames_udaan[0:]:
#     if "xlsb" in file:
#         try:
#             df_inter = wr.s3.read_excel(file, sheet_name=  0)
#             df_inter = df_inter[cols_to_keep]
#             month_udaan = file.split("_")[1]
#             df_inter['month'] = month_udaan
#             df_inter['month'] = pd.to_datetime(df_inter['month'], format = "%d%m%Y")
#             dfs_xlsx.append(df_inter)
#         except:
#             print(file)
#     if "xlsx" in file:
#         try:
#             df_inter = wr.s3.read_excel(file, sheet_name = 0)
#             df_inter = df_inter[cols_to_keep]
#             month_udaan = file.split("_")[1]
#             df_inter['month'] = month_udaan
#             df_inter['month'] = pd.to_datetime(df_inter['month'], format = "%d%m%Y")
#             dfs_xlsx.append(df_inter)
#         except Exception as e:
#             print(e)

In [81]:
# gc.collect()

14148

In [82]:
# data_udaan = pd.concat(dfs_xlsx)

In [83]:
# data_udaan.rename(columns={data_udaan.columns[0]: "pincode",data_udaan.columns[1]: "city",data_udaan.columns[2]: "product_code",data_udaan.columns[3]: "units_sold",data_udaan.columns[4]: "revenue",data_udaan.columns[5]: "sku_name",data_udaan.columns[6]:"month" }, inplace = True)

In [84]:
# data_udaan = data_udaan[['month', 'pincode', 'city', 'product_code', 'units_sold', 'revenue','sku_name']]

In [85]:
# data_udaan

,month,pincode,city,product_code,units_sold,revenue,sku_name
0,2024-01-01,302012,Jaipur,PROD01AKS9XWCCSWM7WW,4,1163.14,IVABID 5 Tablet 14 - EACH of 1
1,2024-01-01,411011,Pune,PROD01AKS9XWCCSWM7WW,1,290.78,IVABID 5 Tablet 14 - EACH of 1
2,2024-01-01,411051,Pune,PROD01AKS9XWCCSWM7WW,1,286.21,IVABID 5 Tablet 14 - EACH of 1
3,2024-01-01,411061,Pune,PROD01AKS9XWCCSWM7WW,2,581.57,IVABID 5 Tablet 14 - EACH of 1
4,2024-01-01,700014,Kolkata,PROD01AKS9XWCCSWM7WW,2,578.52,IVABID 5 Tablet 14 - EACH of 1
...,...,...,...,...,...,...,...
11288,2024-04-01,700159,Kolkata,PRODZUNBYP4MQ125QKTL,2,1343.18,New Pediasure Chocolate (Box) 400 gm Powder -...
11289,2024-04-01,711105,Kolkata,PRODZUNBYP4MQ125QKTL,1,671.59,New Pediasure Chocolate (Box) 400 gm Powder -...
11290,2024-04-01,711109,Kolkata,PRODZUNBYP4MQ125QKTL,4,2686.38,New Pediasure Chocolate (Box) 400 gm Powder -...
11291,2024-04-01,711110,Kolkata,PRODZUNBYP4MQ125QKTL,2,1343.18,New Pediasure Chocolate (Box) 400 gm Powder -...
11292,2024-04-01,711204,Kolkata,PRODZUNBYP4MQ125QKTL,1,671.59,New Pediasure Chocolate (Box) 400 gm Powder -...

In [86]:
# gc.collect()

0

In [87]:
# data_udaan["month"].unique()

<DatetimeArray>
['2024-01-01 00:00:00', '2024-02-01 00:00:00', '2024-03-01 00:00:00',
 '2024-04-01 00:00:00']
Length: 4, dtype: datetime64[ns]

## Wellness

In [96]:
import boto3
s3 = boto3.resource('s3')

## Bucket to use
bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

## List objects within a given prefix
filenames_wellness = [obj.key for obj in bucket.objects.filter(Prefix='raw/From 2026/Wellness')]

In [97]:
filenames_wellness = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_wellness]

In [98]:
filenames_wellness

['s3://abt-aa-india-202005001-nonprod/raw/From 2026/Wellness/',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Wellness/Abbott Feb-26_wellness.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Wellness/Abbott Jan-26_wellness.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Wellness/Abbott Mar-26_wellness.xlsx']

In [99]:
filenames_wellness = filenames_wellness[1:]

In [100]:
gc.collect()

2108

In [101]:
month_list = ["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"]
cols_to_keep = ["Pincode", "City", "Item Code","Sales Qty","Sales Value","Item name"]

In [102]:
dfs_xlsx = []
dfs_xlsb = []
for file in filenames_wellness[0:]:
    if "xlsb" in file:
        try:
            df_inter = wr.s3.read_excel(file)
            df_inter = df_inter[cols_to_keep]
            month_wellness = [x.upper() for x in month_list if x + "-26" in file.lower()]
            df_inter['month'] = month_wellness[0]
            df_inter['month'] = pd.to_datetime("01" + df_inter['month'] + "2026", format = "%d%b%Y")
            dfs_xlsx.append(df_inter)
        except:
            print(file)
    if "xlsx" in file:
        try:
            df_inter = wr.s3.read_excel(file)
            df_inter = df_inter[cols_to_keep]
            month_wellness = [x.upper() for x in month_list if x + "-26" in file.lower()]
            df_inter['month'] = month_wellness[0]
            df_inter['month'] = pd.to_datetime("01" + df_inter['month'] + "2026", format = "%d%b%Y")
            dfs_xlsx.append(df_inter)
        except Exception as e:
            print(e)

In [103]:
gc.collect()

40296

In [104]:
data_wellness = pd.concat(dfs_xlsx)

In [105]:
data_wellness['month'].unique()

<DatetimeArray>
['2026-02-01 00:00:00', '2026-01-01 00:00:00', '2026-03-01 00:00:00']
Length: 3, dtype: datetime64[ns]

In [106]:
data_wellness

,Pincode,City,Item Code,Sales Qty,Sales Value,Item name,month
0,403001,PANJIM,444660,2.0,506.10,TOSSEX SYP 120ML,2026-02-01
1,403001,PANJIM,414678,1.0,155.56,POLIEXAR 2MG 10CAP,2026-02-01
2,403001,PANJIM,418475,8.0,919.99,TIXYLIX CHERRY FLVR CHILD COUGH SYP 60ML,2026-02-01
3,403001,PANJIM,421687,2.0,1014.40,FACECLIN F/WASH 100ML,2026-02-01
4,403001,PANJIM,424148,4.0,1055.50,NEO MERCAZOLE 5MG 130TAB,2026-02-01
...,...,...,...,...,...,...,...
37572,400610,THANE,339290,4.0,1411.09,VERTIN 16MG 15TAB,2026-03-01
37573,400610,THANE,339297,7.0,1395.49,VERTIN 8MG 15TAB,2026-03-01
37574,400610,THANE,348358,1.0,43.87,INDERAL 20MG 15TAB,2026-03-01
37575,400610,THANE,204009,5.0,3779.03,DUPHASTON 10TAB,2026-03-01
37576,400610,THANE,208853,2.0,694.00,NOVELON 21TAB,2026-03-01

In [107]:
#data_wellness.to_csv('wellness.csv')

In [108]:
data_wellness.rename(columns={data_wellness.columns[0]: "pincode",data_wellness.columns[1]: "city",data_wellness.columns[2]: "product_code",data_wellness.columns[3]: "units_sold",data_wellness.columns[4]: "revenue",data_wellness.columns[5]: "sku_name",data_wellness.columns[6]:"month"  }, inplace = True)

In [109]:
data_wellness = data_wellness[['month', 'pincode', 'city', 'product_code', 'units_sold', 'revenue','sku_name']]

In [110]:
data_wellness

,month,pincode,city,product_code,units_sold,revenue,sku_name
0,2026-02-01,403001,PANJIM,444660,2.0,506.10,TOSSEX SYP 120ML
1,2026-02-01,403001,PANJIM,414678,1.0,155.56,POLIEXAR 2MG 10CAP
2,2026-02-01,403001,PANJIM,418475,8.0,919.99,TIXYLIX CHERRY FLVR CHILD COUGH SYP 60ML
3,2026-02-01,403001,PANJIM,421687,2.0,1014.40,FACECLIN F/WASH 100ML
4,2026-02-01,403001,PANJIM,424148,4.0,1055.50,NEO MERCAZOLE 5MG 130TAB
...,...,...,...,...,...,...,...
37572,2026-03-01,400610,THANE,339290,4.0,1411.09,VERTIN 16MG 15TAB
37573,2026-03-01,400610,THANE,339297,7.0,1395.49,VERTIN 8MG 15TAB
37574,2026-03-01,400610,THANE,348358,1.0,43.87,INDERAL 20MG 15TAB
37575,2026-03-01,400610,THANE,204009,5.0,3779.03,DUPHASTON 10TAB
37576,2026-03-01,400610,THANE,208853,2.0,694.00,NOVELON 21TAB

In [111]:
data_wellness.groupby('month')[['units_sold','revenue']].sum()

               units_sold      revenue
month
2026-01-01  169085.488095  30059994.60
2026-02-01  149335.614126  26676892.40
2026-03-01  161965.246666  29691539.59

## Pharmeasy

In [112]:
import boto3
s3 = boto3.resource('s3')

## Bucket to use
bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

## List objects within a given prefix
filenames_Pharmeasy = [obj.key for obj in bucket.objects.filter(Delimiter=',', Prefix='raw/From 2026/Pharmeasy')]

In [113]:
filenames_Pharmeasy = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_Pharmeasy]

In [114]:
filenames_Pharmeasy

['s3://abt-aa-india-202005001-nonprod/raw/From 2026/Pharmeasy/',
 "s3://abt-aa-india-202005001-nonprod/raw/From 2026/Pharmeasy/ABBOTT_Pincode_Wise_Sales_Report_PE_Feb'26_edited.xlsx",
 "s3://abt-aa-india-202005001-nonprod/raw/From 2026/Pharmeasy/ABBOTT_Pincode_Wise_Sales_Report_PE_Jan'26.xlsx",
 "s3://abt-aa-india-202005001-nonprod/raw/From 2026/Pharmeasy/ABBOTT_Pincode_Wise_Sales_Report_PE_Mar'26_edited.xlsx"]

In [115]:
filenames_Pharmeasy = filenames_Pharmeasy[1:]

In [116]:
gc.collect()

2108

In [117]:
cols_to_keep = ["Month","Demand Pincode","Demand City Name","Ucode","Quantity", "Revenue","Product Name"]

In [118]:
dfs_xlsx = []
dfs_xlsb = []
for file in filenames_Pharmeasy[0:]:
    if "xlsb" in file:
        try:
            df_inter = wr.s3.read_excel(file, sheet_name = "Sheet1")
            df_inter = df_inter[cols_to_keep]
            dfs_xlsx.append(df_inter)
        except:
            print(file)
    if "xlsx" in file:
        try:
            df_inter = wr.s3.read_excel(file, sheet_name = "Sheet1")
            df_inter = df_inter[cols_to_keep]
            dfs_xlsx.append(df_inter)
        except Exception as e:
            print(e)

In [119]:
gc.collect()

59188

In [120]:
data_Pharmeasy = pd.concat(dfs_xlsx)

In [121]:
data_Pharmeasy.rename(columns={data_Pharmeasy.columns[0]: "month",data_Pharmeasy.columns[1]: "pincode",data_Pharmeasy.columns[2]: "city",data_Pharmeasy.columns[3]: "product_code",data_Pharmeasy.columns[4]: "units_sold",data_Pharmeasy.columns[5]: "revenue",data_Pharmeasy.columns[6]:"sku_name"  }, inplace = True)

In [122]:
data_Pharmeasy.head(2)

,month,pincode,city,product_code,units_sold,revenue,sku_name
0,2026-02-01,500034,Hyderabad Area,I08644,4,98.72,LIMCEE 500MG ORANGE FLAVOUR CHEWABLE STRIP OF ...
1,2026-02-01,501501,Vikarabad-1,220506,1,313.78,GTN SORBITRATE CR 2.6MG BOTTLE OF 30 TABLETS

In [123]:
data_Pharmeasy['month'].unique()

array(['2026-02-01', '2026-01-01', '2026-03-01'], dtype=object)

In [124]:
gc.collect()

0

In [125]:
data_Pharmeasy.groupby('month')[['units_sold','revenue']].sum()

            units_sold      revenue
month
2026-01-01      176687  52469090.99
2026-02-01      168155  49676165.28
2026-03-01      192204  54629956.34

## Netmeds

In [172]:
import boto3
s3 = boto3.resource('s3')

## Bucket to use
bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

## List objects within a given prefix
filenames_Netmeds = [obj.key for obj in bucket.objects.filter(Delimiter=',', Prefix='raw/From 2026/Netmeds')]

In [173]:
filenames_Netmeds = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_Netmeds]

In [174]:
filenames_Netmeds

['s3://abt-aa-india-202005001-nonprod/raw/From 2026/Netmeds/',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Netmeds/Abbott -Netmeds_Jan_2026.csv',
 "s3://abt-aa-india-202005001-nonprod/raw/From 2026/Netmeds/Abbott_Sales_Feb '26_Netmeds.csv",
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Netmeds/Copy of Abbott_Sales_Data_Mar_2026_Netmeds_edited.csv']

In [175]:
filenames_Netmeds = filenames_Netmeds[1:]

In [176]:
gc.collect()

71529

In [177]:
cols_to_keep = ["Order Date","Shipping to Pincode","Product Code","Purchase Qty","Amount","Order Status","Product Name"]

In [178]:
    dfs_xlsx = []
    dfs_xlsb = []
    for file in filenames_Netmeds[0:]:
        if "xlsx" in file:
            try:
                df_inter = wr.s3.read_excel(file)
                df_inter = df_inter[cols_to_keep]
                dfs_xlsb.append(df_inter)
            except:
                print(file)
        if "csv" in file:
            try:
                df_inter = pd.read_csv(file)
                df_inter = df_inter[cols_to_keep]
                dfs_xlsx.append(df_inter)
            except Exception as e:
                print(e)

In [179]:
gc.collect()

12

In [180]:
data_Netmeds = pd.concat(dfs_xlsx)

In [181]:
data_Netmeds.head()

,Order Date,Shipping to Pincode,Product Code,Purchase Qty,Amount,Order Status,Product Name
0,01/01/2026,334001,937874,10,246.80,Delivered,LIMCEE ORANGE FLAVOUR 500mg Chewable Tablet 15's
1,01/01/2026,110017,42459,4,318.52,Delivered,Stator 10mg Tablet 15'S
2,01/01/2026,248001,361021,3,525.93,Delivered,Esoga RD Capsule 10'S
3,01/01/2026,800001,1183203,2,10276.00,Delivered,FreeStyle Libre 2 Plus Continous Glucose Monit...
4,01/01/2026,110046,937874,1,24.68,Delivered,LIMCEE ORANGE FLAVOUR 500mg Chewable Tablet 15's

In [182]:
data_Netmeds=data_Netmeds.loc[data_Netmeds['Order Status'] == 'Delivered']

In [183]:
data_Netmeds['Order Date'].unique()

array(['01/01/2026', '01-02-26', '01-03-26'], dtype=object)

In [184]:
data_Netmeds.drop(["Order Status"], axis = 1, inplace = True)

In [185]:
data_Netmeds['Order Date'] = pd.to_datetime(data_Netmeds['Order Date'], format = "mixed", dayfirst= True).apply(lambda x: x.replace(day=1))

In [186]:
#data_Netmeds['Order Date'] = pd.to_datetime(data_Netmeds['Order Date'], format='%d-%m-%y', errors='coerce').apply(lambda x: x.replace(day=1) if pd.notnull(x) else x)

In [187]:
data_Netmeds['city'] = 0

In [188]:
data_Netmeds.head()

,Order Date,Shipping to Pincode,Product Code,Purchase Qty,Amount,Product Name,city
0,2026-01-01,334001,937874,10,246.80,LIMCEE ORANGE FLAVOUR 500mg Chewable Tablet 15's,0
1,2026-01-01,110017,42459,4,318.52,Stator 10mg Tablet 15'S,0
2,2026-01-01,248001,361021,3,525.93,Esoga RD Capsule 10'S,0
3,2026-01-01,800001,1183203,2,10276.00,FreeStyle Libre 2 Plus Continous Glucose Monit...,0
4,2026-01-01,110046,937874,1,24.68,LIMCEE ORANGE FLAVOUR 500mg Chewable Tablet 15's,0

In [189]:
data_Netmeds.columns

Index(['Order Date', 'Shipping to Pincode', 'Product Code', 'Purchase Qty',
       'Amount', 'Product Name', 'city'],
      dtype='object')

In [190]:
data_Netmeds.rename(columns={data_Netmeds.columns[0]: "month",data_Netmeds.columns[1]: "pincode",data_Netmeds.columns[2]: "product_code",data_Netmeds.columns[3]: "units_sold",data_Netmeds.columns[4]: "revenue",data_Netmeds.columns[5]: "sku_name",data_Netmeds.columns[6]:"city"  }, inplace = True)

In [191]:
data_Netmeds.head()

,month,pincode,product_code,units_sold,revenue,sku_name,city
0,2026-01-01,334001,937874,10,246.80,LIMCEE ORANGE FLAVOUR 500mg Chewable Tablet 15's,0
1,2026-01-01,110017,42459,4,318.52,Stator 10mg Tablet 15'S,0
2,2026-01-01,248001,361021,3,525.93,Esoga RD Capsule 10'S,0
3,2026-01-01,800001,1183203,2,10276.00,FreeStyle Libre 2 Plus Continous Glucose Monit...,0
4,2026-01-01,110046,937874,1,24.68,LIMCEE ORANGE FLAVOUR 500mg Chewable Tablet 15's,0

In [192]:
data_Netmeds['month'].unique()

<DatetimeArray>
['2026-01-01 00:00:00', '2026-02-01 00:00:00', '2026-03-01 00:00:00']
Length: 3, dtype: datetime64[ns]

In [193]:
data_Netmeds['revenue'] = data_Netmeds['revenue'].astype(int)

In [194]:
data_Netmeds.groupby('month')[['units_sold','revenue']].sum()

            units_sold   revenue
month
2026-01-01       61158  19493175
2026-02-01       55462  13665666
2026-03-01       65931  16976095

## Apollo (New format now)

In [139]:
# import boto3
# s3 = boto3.resource('s3')

# ## Bucket to use
# bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

# ## List objects within a given prefix
# filenames_Apollo = [obj.key for obj in bucket.objects.filter(Delimiter=',', Prefix='raw/From 2024/Apollo')]

In [140]:
# filenames_Apollo = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_Apollo]

In [141]:
# filenames_Apollo = filenames_Apollo[1:]

In [142]:
# filenames_Apollo

In [143]:
gc.collect()

6

In [144]:
gc.collect()

0

In [145]:
# #Reading YTD pickle file
# YTD_apollo=pd.read_pickle('s3://abt-aa-india-202005001-nonprod/raw/From 2024/Apollo/YTD_Apollo/YTD_apollo_v11.pickle')

In [146]:
# #Reading latest apollo file
# Latest_apollo=wr.s3.read_excel(filenames_Apollo[0])
# cols_to_keep = ["MON","PINCODE","CODE","Abbott Sales In Units","Abbott Sales Value","ITEMNAME"]
# Latest_apollo = Latest_apollo[cols_to_keep]
# #Latest_apollo['month'] = pd.to_datetime("01" + Latest_apollo['Month'] , format = "%d%b%Y")

In [147]:
# Latest_apollo['MON'].unique()

In [148]:
# Latest_apollo.columns

In [149]:
# Latest_apollo.rename(columns={Latest_apollo.columns[1]: "pincode",Latest_apollo.columns[2]: "product_code",Latest_apollo.columns[3]: "units_sold",Latest_apollo.columns[4]: "revenue",Latest_apollo.columns[0]: "month",Latest_apollo.columns[5]:"sku_name"}, inplace = True)
# Latest_apollo = Latest_apollo[['month', 'pincode','product_code', 'units_sold', 'revenue','sku_name']]

In [150]:
# Latest_apollo.columns

In [151]:
# #concatting ytd and latest data
# data_apollo = pd.concat([YTD_apollo,Latest_apollo],axis=0)

In [152]:
#data_apollo=Latest_apollo

In [153]:
# data_apollo['city'] = 0

In [154]:
# data_apollo.head()

In [155]:
# data_apollo.groupby('month')['revenue'].sum()

In [156]:
# #Saving YTD apollo file
# data_apollo.to_pickle('s3://abt-aa-india-202005001-nonprod/raw/From 2024/Apollo/YTD_Apollo/YTD_apollo_v12.pickle')

In [157]:
# data_apollo.head()

## Amazon

In [195]:
import boto3
s3 = boto3.resource('s3')

## Bucket to use
bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

## List objects within a given prefix
filenames_amazon = [obj.key for obj in bucket.objects.filter(Prefix='raw/From 2026/amazon')]

In [196]:
filenames_amazon = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_amazon]

In [197]:
filenames_amazon

['s3://abt-aa-india-202005001-nonprod/raw/From 2026/amazon/',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/amazon/Abbott Feb-26_amazon_edited.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/amazon/Abbott Jan-26 Amazon.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/amazon/Abbott Mar-26_amazon_edited.xlsx']

In [198]:
filenames_amazon = filenames_amazon[1:]

In [199]:
gc.collect()

2114

In [200]:
month_list = ["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"]
cols_to_keep = ["ASIN","Units","Sales"]

In [201]:
dfs_xlsx = []
dfs_xlsb = []
for file in filenames_amazon[0:]:
    if "xlsb" in file:
        try:
            df_inter = wr.s3.read_excel(file, sheet_name = "Sheet1",skiprows=1)
            df_inter = df_inter[cols_to_keep]
            month_amazon = [x.upper() for x in month_list if x + "-26" in file.lower()]
            df_inter['month'] = month_amazon[0]
            df_inter['month'] = pd.to_datetime("01" + df_inter['month'] + "2026", format = "%d%b%Y")
            dfs_xlsx.append(df_inter)
        except:
            print(file)
    if "xlsx" in file:
        try:
            df_inter = wr.s3.read_excel(file, sheet_name = "Sheet1",skiprows=1)
            df_inter = df_inter[cols_to_keep]
            month_amazon = [x.upper() for x in month_list if x + "-26" in file.lower()]
            df_inter['month'] = month_amazon[0]
            df_inter['month'] = pd.to_datetime("01" + df_inter['month'] + "2026", format = "%d%b%Y")
            dfs_xlsx.append(df_inter)
        except Exception as e:
            print(e)

In [202]:
gc.collect()

11351

In [203]:
data_amazon = pd.concat(dfs_xlsx)

In [204]:
data_amazon['month'].unique()

<DatetimeArray>
['2026-02-01 00:00:00', '2026-01-01 00:00:00', '2026-03-01 00:00:00']
Length: 3, dtype: datetime64[ns]

In [205]:
data_amazon

            ASIN  Units       Sales      month
0     B086572K3N   8434  2647462.64 2026-02-01
1     B086572K3N   3721  1156854.58 2026-02-01
2     B086572K3N   3241  1022735.09 2026-02-01
3     B086572K3N   2409   759032.00 2026-02-01
4     B085J59HMQ    347   256305.40 2026-02-01
...          ...    ...         ...        ...
1500  B085J8MZY4     16     6906.72 2026-03-01
1501  B0BQC7JP38     12      982.92 2026-03-01
1502  B085J8LQ7Q      2      470.72 2026-03-01
1503  B084BF1XL2      8     1872.40 2026-03-01
1504  B0861Z5QGQ      1      169.03 2026-03-01

[4762 rows x 4 columns]

In [206]:
data_amazon['pincode']=0
data_amazon['city']=0

In [207]:
data_amazon.rename(columns={data_amazon.columns[0]: "product_code",data_amazon.columns[1]: "units_sold",data_amazon.columns[2]: "revenue",data_amazon.columns[3]: "month",data_amazon.columns[4]: "pincode",data_amazon.columns[5]: "city",  }, inplace = True)

In [208]:
data_amazon = data_amazon[['month', 'pincode', 'city', 'product_code', 'units_sold', 'revenue']]

In [209]:
data_amazon

          month  pincode  city product_code  units_sold     revenue
0    2026-02-01        0     0   B086572K3N        8434  2647462.64
1    2026-02-01        0     0   B086572K3N        3721  1156854.58
2    2026-02-01        0     0   B086572K3N        3241  1022735.09
3    2026-02-01        0     0   B086572K3N        2409   759032.00
4    2026-02-01        0     0   B085J59HMQ         347   256305.40
...         ...      ...   ...          ...         ...         ...
1500 2026-03-01        0     0   B085J8MZY4          16     6906.72
1501 2026-03-01        0     0   B0BQC7JP38          12      982.92
1502 2026-03-01        0     0   B085J8LQ7Q           2      470.72
1503 2026-03-01        0     0   B084BF1XL2           8     1872.40
1504 2026-03-01        0     0   B0861Z5QGQ           1      169.03

[4762 rows x 6 columns]

In [211]:
data_amazon.groupby('month')[['revenue','units_sold']].sum()

                revenue  units_sold
month
2026-01-01  18246314.83       93862
2026-02-01  17538740.89       88591
2026-03-01  18570099.87       91146

## Truemeds

In [227]:
import boto3
s3 = boto3.resource('s3')

## Bucket to use
bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

## List objects within a given prefix
filenames_truemeds = [obj.key for obj in bucket.objects.filter(Delimiter=',', Prefix='raw/From 2026/truemeds')]

In [228]:
filenames_truemeds = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_truemeds]

In [229]:
filenames_truemeds

['s3://abt-aa-india-202005001-nonprod/raw/From 2026/truemeds/',
 "s3://abt-aa-india-202005001-nonprod/raw/From 2026/truemeds/Abbott CFA -TM -Jan'26.xlsx",
 "s3://abt-aa-india-202005001-nonprod/raw/From 2026/truemeds/Abbott CFA TM -Feb'26.xlsx",
 "s3://abt-aa-india-202005001-nonprod/raw/From 2026/truemeds/Abbott CFA_Truemeds_march'26_edited.xlsx"]

In [230]:
filenames_truemeds = filenames_truemeds[1:]

In [231]:
gc.collect()

2108

In [232]:
cols_to_keep = ["Date","Billing Zip","Location","Item Code","Quantity Sold", "Item Amount"]

In [244]:
    dfs_xlsx = []
    dfs_xlsb = []
    for file in filenames_truemeds[0:]:
        if "xlsx" in file:
            try:
                df_inter = wr.s3.read_excel(file,sheet_name = "base")
                df_inter = df_inter[cols_to_keep]
                dfs_xlsb.append(df_inter)
            except:
                print(file)
        if "xlsx" in file:
            try:
                df_inter = wr.s3.read_excel(file,sheet_name = "base")
                df_inter = df_inter[cols_to_keep]
                dfs_xlsx.append(df_inter)
            except Exception as e:
                print(e)

In [245]:
gc.collect()

60775

In [246]:
data_truemeds = pd.concat(dfs_xlsx)

In [247]:
data_truemeds

,Date,Billing Zip,Location,Item Code,Quantity Sold,Item Amount
0,2026-01-01,201017,Delhi Okhla,TM-TACR1-039973,1,164.26
1,2026-01-01,201005,Delhi Okhla,TM-TACR1-014181,1,592.14
2,2026-01-01,411045,Pune,TM-TACR1-021892,2,44.08
3,2026-01-01,110013,Delhi Okhla,TM-SYUP1-001315,2,643.45
4,2026-01-01,500018,Hyderabad,TM-POER1-002085,1,549.10
...,...,...,...,...,...,...
58093,2026-03-01,723129,Kolkata Dhulagarh,TM-TACR1-011255,3,90.30
58094,2026-03-01,321609,Delhi Okhla,TM-GEEL1-000412,2,544.14
58095,2026-03-01,848210,Kolkata Dhulagarh,TM-GEEL1-000414,1,272.07
58096,2026-03-01,176063,Delhi Okhla,TM-TACR1-011250,3,90.30
58097,2026-03-01,226029,Lucknow_New,TM-TACR1-011250,1,30.10

In [248]:
data_truemeds['Date'].unique()

<DatetimeArray>
['2026-01-01 00:00:00', '2026-02-16 00:00:00', '2026-02-17 00:00:00',
 '2026-02-18 00:00:00', '2026-02-19 00:00:00', '2026-02-20 00:00:00',
 '2026-02-21 00:00:00', '2026-02-22 00:00:00', '2026-02-23 00:00:00',
 '2026-02-24 00:00:00', '2026-02-25 00:00:00', '2026-02-26 00:00:00',
 '2026-02-27 00:00:00', '2026-02-28 00:00:00', '2026-02-01 00:00:00',
 '2026-02-02 00:00:00', '2026-02-03 00:00:00', '2026-02-04 00:00:00',
 '2026-02-05 00:00:00', '2026-02-06 00:00:00', '2026-02-07 00:00:00',
 '2026-02-08 00:00:00', '2026-02-09 00:00:00', '2026-02-10 00:00:00',
 '2026-02-11 00:00:00', '2026-02-12 00:00:00', '2026-02-13 00:00:00',
 '2026-02-14 00:00:00', '2026-02-15 00:00:00', '2026-03-01 00:00:00']
Length: 30, dtype: datetime64[ns]

In [249]:
data_truemeds['Date'] = pd.to_datetime(data_truemeds['Date']).apply(lambda x: x.replace(day=1))
#data_truemeds['Date']= pd.to_datetime(data_truemeds['Date'])

In [250]:
data_truemeds.rename(columns={data_truemeds.columns[1]: "pincode",data_truemeds.columns[2]: "city",data_truemeds.columns[3]: "product_code",data_truemeds.columns[4]: "units_sold",data_truemeds.columns[5]: "revenue",data_truemeds.columns[0]: "month",  }, inplace = True)

In [251]:
data_truemeds.groupby('month')['revenue'].sum()

month
2026-01-01    28509914.48
2026-02-01    27221745.61
2026-03-01    29909126.93
Name: revenue, dtype: float64

## Zepto

In [252]:
import boto3
s3 = boto3.resource('s3')

## Bucket to use
bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

## List objects within a given prefix
filenames_zepto = [obj.key for obj in bucket.objects.filter(Delimiter=',', Prefix='raw/From 2026/zepto')]

In [253]:
filenames_zepto = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_zepto]

In [254]:
filenames_zepto

['s3://abt-aa-india-202005001-nonprod/raw/From 2026/zepto/',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/zepto/Zepto Offtake_Feb_2026_1.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/zepto/Zepto Offtake_Jan_2026_1.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/zepto/Zepto Offtake_Mar_2026_1.xlsx']

In [255]:
filenames_zepto = filenames_zepto[1:]

In [256]:
gc.collect()

2108

In [257]:
cols_to_keep = ["Date","City","SKU Number","Sales (Qty) - Units", "Gross Merchandise Value"]

In [258]:
    dfs_xlsx = []
    dfs_xlsb = []
    for file in filenames_zepto[0:]:
        if "xlsx" in file:
            try:
                df_inter = wr.s3.read_excel(file)
                df_inter = df_inter[cols_to_keep]
                dfs_xlsb.append(df_inter)
            except:
                print(file)
        if "xlsx" in file:
            try:
                df_inter = wr.s3.read_excel(file)
                df_inter = df_inter[cols_to_keep]
                dfs_xlsx.append(df_inter)
            except Exception as e:
                print(e)

In [259]:
gc.collect()

30493

In [260]:
data_zepto = pd.concat(dfs_xlsx)

In [261]:
data_zepto

,Date,City,SKU Number,Sales (Qty) - Units,Gross Merchandise Value
0,2026-02-01,Bengaluru,8b80c557-3272-4eb9-a49c-a142107aa2e1,150,3702.00
1,2026-02-01,Hyderabad,c9ca8c15-3d56-4b48-a0ca-06494f29a85c,1,180.74
2,2026-02-01,Bengaluru,2fc2e4e8-3f4b-44ac-8e9c-f714140a4f5e,4,3380.00
3,2026-02-01,Mumbai,afe63673-d32f-4ceb-85bd-82fd3807fc2b,13,11960.00
4,2026-02-01,Hyderabad,935fb675-cd2b-417e-8357-de7b3a42c9f5,6,2026.80
...,...,...,...,...,...
20165,2026-03-01,Hubballi,7bb12b6d-bddd-48b4-83d1-da1e408c12c4,1,745.00
20166,2026-03-01,Kolkata,11199019-bd1b-43bf-95f2-745415455c31,1,2105.00
20167,2026-03-01,Noida,935fb675-cd2b-417e-8357-de7b3a42c9f5,1,337.80
20168,2026-03-01,Agra,31832b23-081f-49f7-8519-e52660f10411,1,550.00
20169,2026-03-01,Noida,4920c663-f838-4923-9b07-558a8aded062,1,370.00

In [262]:
data_zepto['Date'].unique()

<DatetimeArray>
['2026-02-01 00:00:00', '2026-01-01 00:00:00', '2026-03-01 00:00:00']
Length: 3, dtype: datetime64[ns]

In [263]:
data_zepto['Date']= pd.to_datetime(data_zepto['Date'])

In [264]:
data_zepto['pincode']=0

In [265]:
data_zepto.head(1)

,Date,City,SKU Number,Sales (Qty) - Units,Gross Merchandise Value,pincode
0,2026-02-01,Bengaluru,8b80c557-3272-4eb9-a49c-a142107aa2e1,150,3702.0,0

In [266]:
data_zepto.rename(columns={data_zepto.columns[1]: "city",data_zepto.columns[2]: "product_code",data_zepto.columns[3]: "units_sold",data_zepto.columns[4]: "revenue",data_zepto.columns[5]: "pincode",data_zepto.columns[0]: "month",  }, inplace = True)

In [267]:
data_zepto.groupby('month')['revenue'].sum()

month
2026-01-01    27126200.37
2026-02-01    27340955.52
2026-03-01    30757718.35
Name: revenue, dtype: float64

## Frankross

In [268]:
import boto3
s3 = boto3.resource('s3')

## Bucket to use
bucket = s3.Bucket('abt-aa-india-202005001-nonprod')

## List objects within a given prefix
filenames_frankross = [obj.key for obj in bucket.objects.filter(Delimiter=',', Prefix='raw/From 2026/Frank Ross')]

In [269]:
filenames_frankross = [r's3://abt-aa-india-202005001-nonprod/' + f for f in filenames_frankross]

In [270]:
filenames_frankross

['s3://abt-aa-india-202005001-nonprod/raw/From 2026/Frank Ross/',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Frank Ross/offtake FrankRoss_Feb 2026.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Frank Ross/offtake FrankRoss_Jan 2026.xlsx',
 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Frank Ross/offtake FrankRoss_Mar 2026_edited.xlsx']

In [271]:
filenames_frankross = filenames_frankross[1:]

In [272]:
gc.collect()

2108

In [273]:
cols_to_keep = ["Month","Br.Code","City","Item Code","Pack Qty", "Sales Value"]

In [274]:
    dfs_xlsx = []
    dfs_xlsb = []
    for file in filenames_frankross[0:]:
        if "xlsx" in file:
            try:
                df_inter = wr.s3.read_excel(file,sheet_name = 0)
                df_inter = df_inter[cols_to_keep]
                dfs_xlsb.append(df_inter)
            except:
                print(file)
        if "xlsx" in file:
            try:
                df_inter = wr.s3.read_excel(file,sheet_name = 0)
                df_inter = df_inter[cols_to_keep]
                dfs_xlsx.append(df_inter)
            except Exception as e:
                print(e)

In [275]:
gc.collect()

19493

In [276]:
data_frankross = pd.concat(dfs_xlsx)

In [277]:
data_frankross

           Month  Br.Code     City Item Code  Pack Qty  Sales Value
0     2026-02-01        1  KOLKATA    I96091       1.0    280.72750
1     2026-02-01        1  KOLKATA    I88561       2.0   1057.80800
2     2026-02-01        1  KOLKATA    I96180       2.0   1163.70500
3     2026-02-01        1  KOLKATA    I04465       6.0    457.79680
4     2026-02-01        1  KOLKATA    P49653      12.0   1124.39840
...          ...      ...      ...       ...       ...          ...
15443 2026-03-01      727  KOLKATA    P29161       2.0    577.60000
15444 2026-03-01      727  KOLKATA    I35474       4.0     83.80600
15445 2026-03-01      727  KOLKATA    P39279       1.0    161.24225
15446 2026-03-01      727  KOLKATA    P40724       1.0    175.40070
15447 2026-03-01      727  KOLKATA    P39299       1.0    394.18150

[47278 rows x 6 columns]

In [278]:
data_frankross['Month'].unique()

<DatetimeArray>
['2026-02-01 00:00:00', '2026-01-01 00:00:00', '2026-03-01 00:00:00']
Length: 3, dtype: datetime64[ns]

In [279]:
data_frankross['vendor']='frankross'

In [280]:
mapping_frankross = 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Static_file_for_offtake_data_process/2026_store_mapping_frankross_wellness.xlsx'
mapping_frankross_file = pd.read_excel(mapping_frankross)
mapping_frankross_file=mapping_frankross_file[['Chain name','branch','PinCode']]

In [281]:
mapping_frankross_file.dtypes

Chain name    object
branch        object
PinCode        int64
dtype: object

In [282]:
data_frankross = pd.merge(left=data_frankross,how='left',
                                 right=mapping_frankross_file, left_on=['vendor','Br.Code'], 
                                 right_on=['Chain name','branch'])

In [283]:
data_frankross = data_frankross.drop(['vendor', 'Chain name','branch','Br.Code'], axis=1)

In [284]:
data_frankross['Month']= pd.to_datetime(data_frankross['Month'])

In [285]:
data_frankross.rename(columns={data_frankross.columns[5]: "pincode",data_frankross.columns[1]: "city",data_frankross.columns[2]: "product_code",data_frankross.columns[3]: "units_sold",data_frankross.columns[4]: "revenue",data_frankross.columns[0]: "month",  }, inplace = True)

In [286]:
data_frankross.groupby('month')['revenue'].sum()

month
2026-01-01    1.673046e+07
2026-02-01    1.518959e+07
2026-03-01    1.537094e+07
Name: revenue, dtype: float64

In [287]:
data_frankross.dtypes

month           datetime64[ns]
city                    object
product_code            object
units_sold             float64
revenue                float64
pincode                float64
dtype: object

## Static Files Mapping

In [288]:
#Static Files for getting unmapped pincodes and products
prod_map_path = 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Static_file_for_offtake_data_process/2026_customer_abbott_code_mapping.xlsx'
product_map = wr.s3.read_excel(prod_map_path)

Pin_state_city_path = 's3://abt-aa-india-202005001-nonprod/raw/From 2026/Static_file_for_offtake_data_process/2026_PinCodes_with_States_and_Districts.csv'
Pin_state_city_data = pd.read_csv(Pin_state_city_path,encoding='unicode_escape')

In [289]:
#changing account names
data_1mg['name of customer'] = '1MG'
# data_apollo['name of customer'] = 'APOLLO RETAIL'
data_medplus['name of customer'] = 'MEDPLUS'
# data_thulasi['name of customer'] = 'THULASI'
data_sasta['name of customer'] = 'FLIPKART HEALTH PLUS'
#data_udaan['name of customer'] = 'UDAAN'
data_wellness['name of customer'] = 'WELLNESS'
data_Pharmeasy['name of customer'] = 'PHARMEASY'
data_truemeds['name of customer'] = 'TRUEMEDS'
data_amazon['name of customer'] = 'AMAZON'
data_zepto['name of customer'] = 'ZEPTO'
data_Netmeds['name of customer'] = 'NETMEDS'
data_frankross['name of customer'] = 'FRANK ROSS'

/tmp/ipykernel_458/1947132185.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_wellness['name of customer'] = 'WELLNESS'
/tmp/ipykernel_458/1947132185.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_amazon['name of customer'] = 'AMAZON'

In [290]:
# #appending datasets
# data_1mg_med = pd.concat([data_1mg, data_medplus])
# #data_1mg_med_apo = pd.concat([data_1mg_med, data_apollo])
# data_1mg_apo_med_sas = pd.concat([data_1mg_med, data_sasta])
# #data_1mg_apo_med_sas_ud = pd.concat([data_1mg_apo_med_sas, data_udaan])
# data_1mg_apo_med_sas_ud_pharm = pd.concat([data_1mg_apo_med_sas, data_Pharmeasy])
# data_1mg_apo_med_sas_ud_pharm_netmed = pd.concat([data_1mg_apo_med_sas_ud_pharm, data_Netmeds])
# data_1mg_apo_med_sas_ud_pharm_netmed_ama = pd.concat([data_1mg_apo_med_sas_ud_pharm_netmed, data_amazon])
# data_1mg_apo_med_sas_ud_pharm_netmed_ama_tru = pd.concat([data_1mg_apo_med_sas_ud_pharm_netmed_ama, data_truemeds])
# data_1mg_apo_med_sas_ud_pharm_netmed_ama_tru_zep = pd.concat([data_1mg_apo_med_sas_ud_pharm_netmed_ama_tru, data_zepto])
# data_1mg_apo_med_sas_ud_pharm_netmed_ama_tru_frank = pd.concat([data_1mg_apo_med_sas_ud_pharm_netmed_ama_tru_zep, data_frankross])
# # Add Thulasi and Apollo later
# offtake_combined_all_channels = pd.concat([data_1mg_apo_med_sas_ud_pharm_netmed_ama_tru_frank, data_wellness])
# # offtake_combined_Jan_Jul_all_channels = pd.concat([data_1mg_apo_med_sas_ud, data_wellness])

In [291]:
# #appending datasets
all_datasets = [data_1mg,data_medplus,data_sasta,data_Pharmeasy,data_Netmeds,data_amazon,data_truemeds,data_zepto,data_frankross,data_wellness]
offtake_combined_all_channels = pd.concat(all_datasets)
offtake_combined_all_channels.shape

(2882485, 8)

In [292]:
#data_Netmeds['name of customer'] = 'NETMEDS'
#offtake_combined_all_channels  = data_Netmeds.copy()

In [293]:
offtake_combined_all_channels.dtypes

month                object
pincode             float64
city                 object
product_code         object
units_sold           object
revenue             float64
sku_name             object
name of customer     object
dtype: object

In [294]:
offtake_combined_all_channels.head()

,month,pincode,city,product_code,units_sold,revenue,sku_name,name of customer
0,2026-02-01 00:00:00,411014.0,pune,800528,2,623.90,CremaGel-L Rectal Gel,1MG
1,2026-02-01 00:00:00,560037.0,bangalore,822193,30,23464.80,"New Follihair Tablet | Strengthens, Stimulate...",1MG
2,2026-02-01 00:00:00,560061.0,bangalore,351840,2,379.40,THYronorm 12.5mcg Tablet,1MG
3,2026-02-01 00:00:00,226003.0,lucknow,184375,3,1305.03,Selsun Suspension Anti Dandruff Shampoo | Hair...,1MG
4,2026-02-01 00:00:00,456010.0,ujjain,357013,1,132.02,THYronorm 50mcg Tablet,1MG

In [295]:
offtake_combined_all_channels['month']= pd.to_datetime(offtake_combined_all_channels['month'])
offtake_combined_all_channels['month'].unique()

<DatetimeArray>
['2026-02-01 00:00:00', '2026-01-01 00:00:00', '2026-03-01 00:00:00']
Length: 3, dtype: datetime64[ns]

In [296]:
offtake_combined_all_channels.dtypes

month               datetime64[ns]
pincode                    float64
city                        object
product_code                object
units_sold                  object
revenue                    float64
sku_name                    object
name of customer            object
dtype: object

In [297]:
offtake_combined_all_channels['name of customer'] = offtake_combined_all_channels['name of customer'].str.lower()

In [298]:
#---------writing temp offtake file - CHange Path
offtake_combined_all_channels.to_pickle('s3://abt-aa-india-202005001-nonprod/raw/From 2026/Temp_Unmapped_Offtake Data/20260414_YTD_Unmapped_Offtake_Temp.pickle')

In [299]:
product_map['Customer'] = product_map['Customer'].str.lower()

In [303]:
#getting Abbott SKU
offtake_combined_all_channels = pd.merge(left=offtake_combined_all_channels, how='left', right=product_map, left_on=['product_code','name of customer'], right_on=['Customer Item Code','Customer'])

In [304]:
#Getting unmapped SKUs
null_product=offtake_combined_all_channels[offtake_combined_all_channels['Customer Item Code'].isnull()]

In [305]:
#Mapping City, State
null_pincode = pd.merge(left=offtake_combined_all_channels, how='left', right=Pin_state_city_data, left_on=['pincode'], right_on=['Pin.Code'])

In [306]:
null_pincode.head(4)

,month,pincode,city,product_code,units_sold,revenue,sku_name,name of customer,Customer_x,Customer Item Code_x,SKU No_x,Customer_y,Customer Item Code_y,SKU No_y,Customer,Customer Item Code,SKU No,Pin.Code,State,District
0,2026-02-01,411014.0,pune,800528,2,623.90,CremaGel-L Rectal Gel,1mg,1mg,800528,2040009409,1mg,800528,2040009409,1mg,800528,2040009409,411014.0,Maharashtra,Pune
1,2026-02-01,560037.0,bangalore,822193,30,23464.80,"New Follihair Tablet | Strengthens, Stimulate...",1mg,1mg,822193,2040007652,1mg,822193,2040007652,1mg,822193,2040007652,560037.0,Karnataka,Bangalore
2,2026-02-01,560061.0,bangalore,351840,2,379.40,THYronorm 12.5mcg Tablet,1mg,1mg,351840,2040006831,1mg,351840,2040006831,1mg,351840,2040006831,560061.0,Karnataka,Bangalore
3,2026-02-01,226003.0,lucknow,184375,3,1305.03,Selsun Suspension Anti Dandruff Shampoo | Hair...,1mg,1mg,184375,2040007876,1mg,184375,2040007876,1mg,184375,2040007876,226003.0,Uttar Pradesh,Lucknow

In [307]:
#Getting unmapped pincodes
null_pincode=null_pincode[null_pincode['Pin.Code'].isnull()]

In [308]:
null_pincode.shape

(438, 20)

In [309]:
null_product.shape

(40155, 17)

In [310]:
#writing out files
null_pincode.to_csv("null_pincode.csv")
null_product.to_csv("null_product.csv")

#### End Script ####

In [328]:
# del data_1mg
del data_1mg_apo
del data_1mg_apo_med
del data_1mg_apo_med_sas
# del data_apollo
del data_medplus
del data_sasta
del data_udaan
del data_wellness
del filenames_1mg
del filenames_medplus
del filenames_sasta
del filenames_udaan
del filenames_wellness
del data_Pharmeasy

NameError: name 'data_1mg_apo' is not defined

In [ ]:
gc.collect()

In [ ]:
offtake_combined_all_channels.dtypes

In [ ]:
product_map.dtypes

In [ ]:
product_map.head()

In [ ]:
product_map['SKU No1'] = pd.to_numeric(product_map['SKU No'], errors='coerce')
product_map['SKU Number'] = np.where(product_map['SKU No1'].isna() ,product_map['SKU No'], product_map['SKU No1'])
product_map = product_map.drop(['SKU No', 'SKU No1'], axis=1)
product_map = product_map.rename(columns={'SKU Number': 'SKU No'})

In [ ]:
#getting abbott sku code
offtake_combined_all_channels_with_abbott_code = pd.merge(left=offtake_combined_all_channels, 
                                                          how='left', 
                                                          right=product_map, 
                                                          left_on=['product_code','name of customer'], right_on=['Customer Item Code','Customer'])

In [ ]:
offtake_combined_all_channels_with_abbott_code.head()

In [ ]:
sum(offtake_combined_all_channels.loc[(offtake_combined_all_channels['month'] == '2023-07-01') & (offtake_combined_all_channels['name of customer'] == '1mg'), "revenue"])

In [ ]:
sum(pd.isna(offtake_combined_all_channels_with_abbott_code['SKU No'])), offtake_combined_all_channels_with_abbott_code.shape

In [ ]:
#cleaning conversion dataset
conversion_master_data['Customer'] = conversion_master_data['Customer'].str.lower()

In [ ]:
gc.collect()

In [ ]:
price_data.head()

In [ ]:
price_data['sap_code1'] = pd.to_numeric(price_data['sap_code'], errors='coerce')
price_data['SKU Number'] = np.where(price_data['sap_code1'].isna() ,price_data['sap_code'], price_data['sap_code1'])
price_data = price_data.drop(['sap_code1', 'sap_code'], axis=1)
price_data = price_data.rename(columns={'SKU Number': 'sap_code'})

In [ ]:
#joining price data for PTS
offtake_data_complete = pd.merge(left=offtake_combined_all_channels_with_abbott_code,how='left',
                                 right=price_data, left_on=['SKU No','month'], 
                                 right_on=['sap_code','month'])

In [ ]:
offtake_data_complete.head()

In [ ]:
sum(offtake_data_complete['PTS']==0), offtake_data_complete.shape

In [161]:
conversion_master_data.head()

  Customer Channel Product Code  Conversion Factor
0      1mg               174923                1.0
1      1mg               315841                1.0
2      1mg                38193                1.0
3      1mg               165629                1.0
4      1mg               249830                1.0

In [162]:
#joining conversion master
offtake_data_complete = pd.merge(left=offtake_data_complete, right=conversion_master_data, how='left', 
                                 left_on=['name of customer','product_code'], 
                                 right_on=['Customer','Channel Product Code'])

In [163]:
offtake_data_complete["name of customer"].unique()

array(['1mg', 'medplus', 'apollo retail', 'flipkart health plus', 'udaan',
       'pharmeasy', 'netmeds', 'wellness'], dtype=object)

In [164]:
offtake_data_complete.head(10)

,month,pincode,city,product_code,units_sold,revenue,name of customer,Customer_x,Customer Item Code,SKU No,PTS,sap_code,Customer_y,Channel Product Code,Conversion Factor
0,2023-04-01,380054.0,AHMEDABAD,10392,2.0,474.272612,1mg,1mg,10392,2040005117.0,291.45,2040005117.0,1mg,10392,1.0
1,2023-04-01,277207.0,BALLIA,10392,2.0,472.920000,1mg,1mg,10392,2040005117.0,291.45,2040005117.0,1mg,10392,1.0
2,2023-04-01,751001.0,BHUBANESHWAR,10392,2.0,472.920000,1mg,1mg,10392,2040005117.0,291.45,2040005117.0,1mg,10392,1.0
3,2023-04-01,751024.0,BHUBANESHWAR,10392,3.0,712.380000,1mg,1mg,10392,2040005117.0,291.45,2040005117.0,1mg,10392,1.0
4,2023-04-01,110017.0,DELHI,10392,6.0,1421.760000,1mg,1mg,10392,2040005117.0,291.45,2040005117.0,1mg,10392,1.0
5,2023-04-01,110025.0,DELHI,10392,2.0,475.920000,1mg,1mg,10392,2040005117.0,291.45,2040005117.0,1mg,10392,1.0
6,2023-04-01,110067.0,DELHI,10392,3.0,713.793779,1mg,1mg,10392,2040005117.0,291.45,2040005117.0,1mg,10392,1.0
7,2023-04-01,110077.0,DELHI,10392,6.0,1421.760000,1mg,1mg,10392,2040005117.0,291.45,2040005117.0,1mg,10392,1.0
8,2023-04-01,110080.0,DELHI,10392,2.0,472.920000,1mg,1mg,10392,2040005117.0,291.45,2040005117.0,1mg,10392,1.0
9,2023-04-01,110091.0,DELHI,10392,2.0,475.920000,1mg,1mg,10392,2040005117.0,291.45,2040005117.0,1mg,10392,1.0

In [165]:
#cond.shape

In [166]:
#filtering where conversion factor exists
cond = offtake_data_complete['Conversion Factor'].isnull() == False

In [167]:
offtake_data_complete.drop(['product_code','Customer Item Code','sap_code', 'Customer_x', 'Customer_y','Channel Product Code'], axis = 1, inplace = True)

In [168]:
#converting columns
offtake_data_complete['units_sold'] = pd.to_numeric(offtake_data_complete['units_sold'], errors='coerce').astype('float')

In [169]:
#converting values by conversion factory
offtake_data_complete['final_converted_quantity'] = (offtake_data_complete.units_sold / offtake_data_complete['Conversion Factor']).where(cond,offtake_data_complete.units_sold)
offtake_data_complete['channel_sales'] = offtake_data_complete.final_converted_quantity * offtake_data_complete['PTS']

In [170]:
offtake_data_complete.drop(['revenue'], axis = 1, inplace = True)

In [171]:
offtake_data_complete.head()

,month,pincode,city,units_sold,name of customer,SKU No,PTS,Conversion Factor,final_converted_quantity,channel_sales
0,2023-04-01,380054.0,AHMEDABAD,2.0,1mg,2040005117.0,291.45,1.0,2.0,582.9
1,2023-04-01,277207.0,BALLIA,2.0,1mg,2040005117.0,291.45,1.0,2.0,582.9
2,2023-04-01,751001.0,BHUBANESHWAR,2.0,1mg,2040005117.0,291.45,1.0,2.0,582.9
3,2023-04-01,751024.0,BHUBANESHWAR,3.0,1mg,2040005117.0,291.45,1.0,3.0,874.35
4,2023-04-01,110017.0,DELHI,6.0,1mg,2040005117.0,291.45,1.0,6.0,1748.7

In [172]:
offtake_data_complete.drop(["Conversion Factor", "final_converted_quantity"], axis = 1, inplace = True)

In [173]:
offtake_data_complete['ECB_Primary_Sales'] = 0
offtake_data_complete['Zone'] = 0
offtake_data_complete['Customer Code'] = 0
offtake_data_complete['Customer Name (Sold to Party)'] = 0
offtake_data_complete['CFA Name'] = 0
eap_primary_sales_data['units_sold'] = 0
eap_primary_sales_data['PTS'] = 0

In [174]:
#ordering columns
offtake_data_complete = offtake_data_complete[['month', 'Customer Code', 'pincode', 'Zone',
       'Customer Name (Sold to Party)', 'CFA Name', 'name of customer',
       'SKU No', 'channel_sales', 'ECB_Primary_Sales', 'units_sold', 'PTS']]

In [175]:
eap_primary_sales_data.dtypes

month                            datetime64[ns]
Customer Code                            object
pincode                                   int64
Zone                                     object
Customer Name (Sold to Party)            object
CFA Name                                 object
name of customer                         object
SKU No                                    int64
channel_sales                             int64
ECB_Primary_Sales                       float64
units_sold                                int64
PTS                                       int64
dtype: object

In [176]:
offtake_data_complete.dtypes

month                            datetime64[ns]
Customer Code                             int64
pincode                                 float64
Zone                                      int64
Customer Name (Sold to Party)             int64
CFA Name                                  int64
name of customer                         object
SKU No                                   object
channel_sales                            object
ECB_Primary_Sales                         int64
units_sold                              float64
PTS                                      object
dtype: object

In [177]:
gc.collect()

154

In [178]:
offtake_data_complete['channel_sales'] = offtake_data_complete.fillna(0)['channel_sales']
offtake_data_complete['PTS'] = offtake_data_complete.fillna(0)['PTS']

In [179]:
#QC
sum(offtake_data_complete.loc[(offtake_data_complete['month'] == '2023-04-01') , "channel_sales"])

254884070.53533217

In [180]:
#QC
sum(offtake_data_complete.loc[(offtake_data_complete['month'] == '2023-03-01') , "channel_sales"])

711220263.4144787

In [181]:
#QC
sum(offtake_data_complete.loc[(offtake_data_complete['month'] == '2023-10-01') & (offtake_data_complete['name of customer'] == 'pharmeasy'), "channel_sales"])

22405549.878666695

In [182]:
eap_primary_sales_data.dtypes

month                            datetime64[ns]
Customer Code                            object
pincode                                   int64
Zone                                     object
Customer Name (Sold to Party)            object
CFA Name                                 object
name of customer                         object
SKU No                                    int64
channel_sales                             int64
ECB_Primary_Sales                       float64
units_sold                                int64
PTS                                       int64
dtype: object

In [183]:
offtake_data_complete.dtypes

month                            datetime64[ns]
Customer Code                             int64
pincode                                 float64
Zone                                      int64
Customer Name (Sold to Party)             int64
CFA Name                                  int64
name of customer                         object
SKU No                                   object
channel_sales                           float64
ECB_Primary_Sales                         int64
units_sold                              float64
PTS                                     float64
dtype: object

In [184]:
#appending ECB primary sales
offtake_data_complete1 = pd.concat([offtake_data_complete, eap_primary_sales_data])

In [185]:
sum(offtake_data_complete1.loc[(offtake_data_complete1['month'] == '2023-03-01') , "ECB_Primary_Sales"])

679258743.0

In [186]:
offtake_data_complete1.head()

,month,Customer Code,pincode,Zone,Customer Name (Sold to Party),CFA Name,name of customer,SKU No,channel_sales,ECB_Primary_Sales,units_sold,PTS
0,2023-04-01,0,380054.0,0,0,0,1mg,2040005117.0,582.90,0.0,2.0,291.45
1,2023-04-01,0,277207.0,0,0,0,1mg,2040005117.0,582.90,0.0,2.0,291.45
2,2023-04-01,0,751001.0,0,0,0,1mg,2040005117.0,582.90,0.0,2.0,291.45
3,2023-04-01,0,751024.0,0,0,0,1mg,2040005117.0,874.35,0.0,3.0,291.45
4,2023-04-01,0,110017.0,0,0,0,1mg,2040005117.0,1748.70,0.0,6.0,291.45

In [187]:
offtake_data_complete1['channel_sales'] = offtake_data_complete1.fillna(0)['channel_sales']
offtake_data_complete1['ECB_Primary_Sales'] = offtake_data_complete1.fillna(0)['ECB_Primary_Sales']

In [188]:
#QC
sum(offtake_data_complete1.loc[(offtake_data_complete1['month'] == '2023-10-01') , "channel_sales"])

775819371.4436475

In [189]:
brand_division_data.head()

,SKU Code,Merged SKU Code,Division Name,Brand Name,SKU Name,Affiliate
0,2200000725,2200000725,GI Optima,DIGENE TAB,DIGENE TAB MINT 15T MINIDANGLER,AIL
1,2040000185,2040000185,LifeCare,ANETOL,ANETOL,ASC
2,2040012419,2040012419,FUTURA,PAZROTO,Pazroto 200 mg 30s Tab,ASC
3,2040000183,2040000183,LifeCare,SURVANTA,SURVANTA 8ML,ASC
4,2040000189,2040000189,LifeCare,ALUVIA,ALUVIA TAB 120s(New),ASC

In [190]:
brand_division_data.dtypes

SKU Code           object
Merged SKU Code    object
Division Name      object
Brand Name         object
SKU Name           object
Affiliate          object
dtype: object

In [191]:
brand_division_data['sap_code1'] = pd.to_numeric(brand_division_data['SKU Code'], errors='coerce')
brand_division_data['SKU Number'] = np.where(brand_division_data['sap_code1'].isna() ,brand_division_data['SKU Code'], brand_division_data['sap_code1'])
brand_division_data = brand_division_data.drop(['sap_code1', 'SKU Code'], axis=1)
brand_division_data = brand_division_data.rename(columns={'SKU Number': 'SKU Code'})

In [192]:
#merging bradn division mapping to complete data
offtake_data_complete100 = pd.merge(left=offtake_data_complete1, 
                                    right=brand_division_data.loc[brand_division_data['Division Name']!=0], 
                                    how='left', 
                                    left_on='SKU No', right_on='SKU Code')

In [193]:
offtake_data_complete100.head()

,month,Customer Code,pincode,Zone,Customer Name (Sold to Party),CFA Name,name of customer,SKU No,channel_sales,ECB_Primary_Sales,units_sold,PTS,Merged SKU Code,Division Name,Brand Name,SKU Name,Affiliate,SKU Code
0,2023-04-01,0,380054.0,0,0,0,1mg,2040005117.0,582.90,0.0,2.0,291.45,2040005117,Abbott Victora,UVOX,UVOX 100 MG 10S,ASC,2040005117.0
1,2023-04-01,0,277207.0,0,0,0,1mg,2040005117.0,582.90,0.0,2.0,291.45,2040005117,Abbott Victora,UVOX,UVOX 100 MG 10S,ASC,2040005117.0
2,2023-04-01,0,751001.0,0,0,0,1mg,2040005117.0,582.90,0.0,2.0,291.45,2040005117,Abbott Victora,UVOX,UVOX 100 MG 10S,ASC,2040005117.0
3,2023-04-01,0,751024.0,0,0,0,1mg,2040005117.0,874.35,0.0,3.0,291.45,2040005117,Abbott Victora,UVOX,UVOX 100 MG 10S,ASC,2040005117.0
4,2023-04-01,0,110017.0,0,0,0,1mg,2040005117.0,1748.70,0.0,6.0,291.45,2040005117,Abbott Victora,UVOX,UVOX 100 MG 10S,ASC,2040005117.0

In [194]:
offtake_data_complete100.drop(["SKU Code"], axis = 1, inplace = True)

In [195]:
#QC
sum(offtake_data_complete.loc[(offtake_data_complete['month'] == '2023-10-01') , "channel_sales"])

775819371.4436475

In [196]:
gc.collect()

112

In [197]:
# run this code after placing the Pin code-City_State mapping file

In [198]:
pin_city_state_mapping_path = 's3://abt-aa-india-202005001-nonprod/raw/From 2023/Static_file_for_offtake_data_process/2023_PinCodes_with_States_and_Districts.csv'
pin_city_state_mapping_data = wr.s3.read_csv(pin_city_state_mapping_path, encoding='unicode_escape')

In [199]:
pin_city_state_mapping_data.dtypes
#pin_city_state_mapping_data.head()

Pin.Code     int64
State       object
District    object
dtype: object

In [200]:
del offtake_data_complete1

In [201]:
offtake_data_complete100.dtypes

month                            datetime64[ns]
Customer Code                            object
pincode                                 float64
Zone                                     object
Customer Name (Sold to Party)            object
CFA Name                                 object
name of customer                         object
SKU No                                   object
channel_sales                           float64
ECB_Primary_Sales                       float64
units_sold                              float64
PTS                                     float64
Merged SKU Code                          object
Division Name                            object
Brand Name                               object
SKU Name                                 object
Affiliate                                object
dtype: object

In [202]:
#merging with pin-city-state data
offtake_data_complete100 = pd.merge(left=offtake_data_complete100, right=pin_city_state_mapping_data, 
                                    how='left', 
                                    left_on=['pincode'], right_on=['Pin.Code'])

In [203]:
offtake_data_complete100.head()

,month,Customer Code,pincode,Zone,Customer Name (Sold to Party),CFA Name,name of customer,SKU No,channel_sales,ECB_Primary_Sales,units_sold,PTS,Merged SKU Code,Division Name,Brand Name,SKU Name,Affiliate,Pin.Code,State,District
0,2023-04-01,0,380054.0,0,0,0,1mg,2040005117.0,582.90,0.0,2.0,291.45,2040005117,Abbott Victora,UVOX,UVOX 100 MG 10S,ASC,380054.0,Gujarat,Ahmedabad
1,2023-04-01,0,277207.0,0,0,0,1mg,2040005117.0,582.90,0.0,2.0,291.45,2040005117,Abbott Victora,UVOX,UVOX 100 MG 10S,ASC,277207.0,Uttar Pradesh,Ballia
2,2023-04-01,0,751001.0,0,0,0,1mg,2040005117.0,582.90,0.0,2.0,291.45,2040005117,Abbott Victora,UVOX,UVOX 100 MG 10S,ASC,751001.0,Odisha,Khorda
3,2023-04-01,0,751024.0,0,0,0,1mg,2040005117.0,874.35,0.0,3.0,291.45,2040005117,Abbott Victora,UVOX,UVOX 100 MG 10S,ASC,751024.0,Odisha,Khorda
4,2023-04-01,0,110017.0,0,0,0,1mg,2040005117.0,1748.70,0.0,6.0,291.45,2040005117,Abbott Victora,UVOX,UVOX 100 MG 10S,ASC,110017.0,Delhi,Delhi

In [204]:
offtake_data_complete100.drop(["Pin.Code" ], axis = 1, inplace = True)

In [205]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-01-01'), "ECB_Primary_Sales"])

759481841.0

In [206]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-01-01'), "channel_sales"])

673314159.9264884

In [207]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-02-01'), "channel_sales"])

221981677.07822612

In [208]:
offtake_data_complete100['Division Name'].unique()

array(['Abbott Victora', 'CCD CORDIS', 'Osvita', 'Novacare', 'Invicta',
       'NeuroLife', 'Restora', 'GI Prospera', 'CCD THROMBIS', 'Infinia',
       'Endura', 'Diabetes Maximus', 'General Medicine', 'Xtentia',
       'Respicare', 'Metabolics', 'Derma Magna', 'GI Maxima', 'GI Optima',
       'Multi Therapy', 'Orocare', 'Derma Prime', nan, 'Diabetes Primus',
       'AbSure', 'GenNext', 'FUTURA', 'WH- Mitera', 'Derma Amore',
       'GI Prima', 'Insulin', 'Abbott Spectra', 'Not Found', 'APC_ARDX',
       'Janus', 'Vaccines', 'Hospital Care', 'LifeCare',
       'EPD-Nepal           ', 'GI Advance'], dtype=object)

In [209]:
offtake_data_complete100['Division Name'] = offtake_data_complete100['Division Name'].str.upper()
offtake_data_complete100['name of customer'] = offtake_data_complete100['name of customer'].str.upper()

In [210]:
offtake_data_complete100['Division Name'] = offtake_data_complete100['Division Name'].replace(['VACCINE'],'VACCINES')
offtake_data_complete100['Division Name'] = offtake_data_complete100['Division Name'].replace(['MULTITHERAPY'],'MULTI THERAPY')
offtake_data_complete100['Division Name'] = offtake_data_complete100['Division Name'].replace(['CONSUMERCARE'],'CONSUMER CARE')
offtake_data_complete100['Division Name'] = offtake_data_complete100['Division Name'].replace(['GENERICS'],'ABSURE')

In [211]:
offtake_data_complete100['name of customer'] = offtake_data_complete100['name of customer'].replace(['FRANK-ROSE'],'FRANK ROSS')
offtake_data_complete100['name of customer'] = offtake_data_complete100['name of customer'].replace(['MEDLIFE+PHARMEASY'],'PHARMEASY')
offtake_data_complete100['name of customer'] = offtake_data_complete100['name of customer'].replace(['MEDLIFE'],'PHARMEASY')
offtake_data_complete100['name of customer'] = offtake_data_complete100['name of customer'].replace(['APOLLO'],'APOLLO RETAIL')
offtake_data_complete100['name of customer'] = offtake_data_complete100['name of customer'].replace('APOLLO RETAIL ( 35% OF BUSINESS CAPTURED)', 'APOLLO RETAIL')
offtake_data_complete100['name of customer'] = offtake_data_complete100['name of customer'].replace(['TATA 1MG'],'1MG')
offtake_data_complete100['name of customer'] = offtake_data_complete100['name of customer'].replace(['FLIPKART HEALTH +'],'FLIPKART HEALTH PLUS')
offtake_data_complete100['name of customer'] = offtake_data_complete100['name of customer'].replace(['MEDPLUS (EXCLUSIVE ASC BILLING )'],'MEDPLUS')

In [212]:
offtake_data_complete100['name of customer'].unique()

array(['1MG', 'MEDPLUS', 'APOLLO RETAIL', 'FLIPKART HEALTH PLUS', 'UDAAN',
       'PHARMEASY', 'NETMEDS', 'WELLNESS', 'TRUEMEDS', 'ASTER',
       'ZENO HEALTH', 'FRANK ROSS', 'THULASI', 'EASYMEDICO', 'SAVEO',
       'DAWADOST', 'APANA CHEMIST', 'AMAZON & FLIPKART', 'NOBLE', 'ASWAS'],
      dtype=object)

In [213]:
offtake_data_complete100["Division Name"].unique()

array(['ABBOTT VICTORA', 'CCD CORDIS', 'OSVITA', 'NOVACARE', 'INVICTA',
       'NEUROLIFE', 'RESTORA', 'GI PROSPERA', 'CCD THROMBIS', 'INFINIA',
       'ENDURA', 'DIABETES MAXIMUS', 'GENERAL MEDICINE', 'XTENTIA',
       'RESPICARE', 'METABOLICS', 'DERMA MAGNA', 'GI MAXIMA', 'GI OPTIMA',
       'MULTI THERAPY', 'OROCARE', 'DERMA PRIME', nan, 'DIABETES PRIMUS',
       'ABSURE', 'GENNEXT', 'FUTURA', 'WH- MITERA', 'DERMA AMORE',
       'GI PRIMA', 'INSULIN', 'ABBOTT SPECTRA', 'NOT FOUND', 'APC_ARDX',
       'JANUS', 'VACCINES', 'HOSPITAL CARE', 'LIFECARE',
       'EPD-NEPAL           ', 'GI ADVANCE'], dtype=object)

In [214]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-02-01'), "channel_sales"])

221981677.07822612

In [215]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-03-01'), "channel_sales"])

711226473.7091453

In [216]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-01-01'), "channel_sales"])

673314159.9264884

In [217]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-04-01'), "channel_sales"])

254884070.53533217

In [218]:
#setting offtake = ecb primary (for some accounts and divisions)
offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'ASTER', 'channel_sales'] = offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'ASTER', 'ECB_Primary_Sales']
offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'TRUEMEDS', 'channel_sales'] = offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'TRUEMEDS', 'ECB_Primary_Sales']
offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'SASTA AROGYA', 'channel_sales'] = offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'SASTA AROGYA', 'ECB_Primary_Sales']
offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'GUARDIAN', 'channel_sales'] = offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'GUARDIAN', 'ECB_Primary_Sales']
offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'THULASI', 'channel_sales'] = offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'THULASI', 'ECB_Primary_Sales']
offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'ZENO HEALTH', 'channel_sales'] = offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'ZENO HEALTH', 'ECB_Primary_Sales']
offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'AMAZON & FLIPKART', 'channel_sales'] = offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'AMAZON & FLIPKART', 'ECB_Primary_Sales']
offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'EASYMEDICO', 'channel_sales'] = offtake_data_complete100.loc[offtake_data_complete100['name of customer'] == 'EASYMEDICO', 'ECB_Primary_Sales']

In [219]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-02-01'), "channel_sales"])

233507614.07822612

In [220]:
offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'FRANK ROSS') & (offtake_data_complete100['month'] >= '2022-01-01'), 'channel_sales'] = offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'FRANK ROSS') & (offtake_data_complete100['month'] >= '2022-01-01'), 'ECB_Primary_Sales']
offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'PHARMEASY') & (offtake_data_complete100['month'] <= '2022-04-01'), 'channel_sales'] = offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'PHARMEASY') & (offtake_data_complete100['month'] <= '2022-04-01'), 'ECB_Primary_Sales']
offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'NETMEDS') & (offtake_data_complete100['month'] < '2022-08-01'), 'channel_sales'] = offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'NETMEDS') & (offtake_data_complete100['month'] < '2022-08-01'), 'ECB_Primary_Sales']
offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == '1MG') & (offtake_data_complete100['month'] >= '2022-07-01') & (offtake_data_complete100['Division Name'] == 'INSULIN'), 'channel_sales'] = offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == '1MG') & (offtake_data_complete100['month'] >= '2022-07-01') & (offtake_data_complete100['Division Name'] == 'INSULIN'), 'ECB_Primary_Sales']
offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'PHARMEASY') & (offtake_data_complete100['month'] >= '2022-05-01') & (offtake_data_complete100['Division Name'] == 'INSULIN'), 'channel_sales'] = offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'PHARMEASY') & (offtake_data_complete100['month'] >= '2022-05-01') & (offtake_data_complete100['Division Name'] == 'INSULIN'), 'ECB_Primary_Sales']
offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'WELLNESS') & (offtake_data_complete100['month'] >= '2022-03-01') & (offtake_data_complete100['Division Name'] == 'INSULIN'), 'channel_sales'] = offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'WELLNESS') & (offtake_data_complete100['month'] >= '2022-03-01') & (offtake_data_complete100['Division Name'] == 'INSULIN'), 'ECB_Primary_Sales']
offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'MEDPLUS') & (offtake_data_complete100['month'] >= '2022-05-01') & (offtake_data_complete100['Division Name'] == 'INSULIN'), 'channel_sales'] = offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'MEDPLUS') & (offtake_data_complete100['month'] >= '2022-05-01') & (offtake_data_complete100['Division Name'] == 'INSULIN'), 'ECB_Primary_Sales']
offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'FLIPKART HEALTH PLUS') & (offtake_data_complete100['month'] >= '2022-03-01') & (offtake_data_complete100['Division Name'] == 'INSULIN'), 'channel_sales'] = offtake_data_complete100.loc[(offtake_data_complete100['name of customer'] == 'FLIPKART HEALTH PLUS') & (offtake_data_complete100['month'] >= '2022-03-01') & (offtake_data_complete100['Division Name'] == 'INSULIN'), 'ECB_Primary_Sales']

In [221]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-01-01'), "channel_sales"])

1015399984.9864885

In [222]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-02-01'), "channel_sales"])

497063555.5982263

In [223]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-03-01'), "channel_sales"])

995326359.5291452

In [224]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-04-01'), "channel_sales"])

563790166.7053317

In [225]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-06-01'), "channel_sales"])

525979670.7355517

In [226]:
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-06-01') & (offtake_data_complete100['name of customer']=='1MG' ), "channel_sales"])

43069167.18835956

In [227]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-07-01'), "channel_sales"])

1093510065.0434165

In [228]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-10-01'), "channel_sales"])

1017891946.6849838

In [229]:
#QC
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-05-01') & (offtake_data_complete100['Division Name'] != 'MULTI THERAPY'), "channel_sales"])

472565014.7713945

In [230]:
offtake_data_complete100.columns

Index(['month', 'Customer Code', 'pincode', 'Zone',
       'Customer Name (Sold to Party)', 'CFA Name', 'name of customer',
       'SKU No', 'channel_sales', 'ECB_Primary_Sales', 'units_sold', 'PTS',
       'Merged SKU Code', 'Division Name', 'Brand Name', 'SKU Name',
       'Affiliate', 'State', 'District'],
      dtype='object')

In [231]:
offtake_data_complete100['Division Name'].unique()

array(['ABBOTT VICTORA', 'CCD CORDIS', 'OSVITA', 'NOVACARE', 'INVICTA',
       'NEUROLIFE', 'RESTORA', 'GI PROSPERA', 'CCD THROMBIS', 'INFINIA',
       'ENDURA', 'DIABETES MAXIMUS', 'GENERAL MEDICINE', 'XTENTIA',
       'RESPICARE', 'METABOLICS', 'DERMA MAGNA', 'GI MAXIMA', 'GI OPTIMA',
       'MULTI THERAPY', 'OROCARE', 'DERMA PRIME', nan, 'DIABETES PRIMUS',
       'ABSURE', 'GENNEXT', 'FUTURA', 'WH- MITERA', 'DERMA AMORE',
       'GI PRIMA', 'INSULIN', 'ABBOTT SPECTRA', 'NOT FOUND', 'APC_ARDX',
       'JANUS', 'VACCINES', 'HOSPITAL CARE', 'LIFECARE',
       'EPD-NEPAL           ', 'GI ADVANCE'], dtype=object)

In [232]:
offtake_data_complete100['Brand Name']=offtake_data_complete100['Brand Name'].str.upper()

In [233]:
offtake_data_complete100['name of customer'].unique()

array(['1MG', 'MEDPLUS', 'APOLLO RETAIL', 'FLIPKART HEALTH PLUS', 'UDAAN',
       'PHARMEASY', 'NETMEDS', 'WELLNESS', 'TRUEMEDS', 'ASTER',
       'ZENO HEALTH', 'FRANK ROSS', 'THULASI', 'EASYMEDICO', 'SAVEO',
       'DAWADOST', 'APANA CHEMIST', 'AMAZON & FLIPKART', 'NOBLE', 'ASWAS'],
      dtype=object)

In [234]:
#write output for qc
#offtake_data_complete100.to_csv('test_v10.csv',index=False)

### Quality Checks

In [235]:
channelqc = offtake_data_complete100.groupby(['name of customer','month']).agg(Channel_Sales = ('channel_sales','sum'),
                                                                            ECB_Primary_Sales = ('ECB_Primary_Sales','sum')).reset_index()

channeldivqc = offtake_data_complete100.groupby(['name of customer','Division Name','month']).agg(Channel_Sales = ('channel_sales','sum'),
                                                                            ECB_Primary_Sales = ('ECB_Primary_Sales','sum')).reset_index()

In [236]:
channelqc

    name of customer      month  Channel_Sales  ECB_Primary_Sales
0                1MG 2023-01-01   7.517253e+07        73664211.00
1                1MG 2023-02-01   5.096328e+07        46108095.00
2                1MG 2023-03-01   7.296225e+07        71332895.00
3                1MG 2023-04-01   5.374135e+07        53807994.01
4                1MG 2023-05-01   3.815374e+07        26264232.00
..               ...        ...            ...                ...
166      ZENO HEALTH 2023-07-01   1.992370e+06         1992369.94
167      ZENO HEALTH 2023-08-01   2.023928e+06         2023928.00
168      ZENO HEALTH 2023-09-01   1.010803e+06         1010803.00
169      ZENO HEALTH 2023-10-01   1.848864e+06         1848864.08
170      ZENO HEALTH 2023-11-01   2.399126e+06         2399126.00

[171 rows x 4 columns]

In [237]:
#writing out qc in excel file
with pd.ExcelWriter("Offtake_QC.xlsx") as writer:
    channelqc.to_excel(writer, sheet_name = "Account Sales", index = False)
    channeldivqc.to_excel(writer, sheet_name = "Account_Division Sales", index = False)

In [238]:
offtake_data_complete100.to_csv('test.csv',index=False)

In [239]:
#writing out final file after qc
offtake_data_complete100.to_csv('s3://abt-aa-india-202005001-nonprod/outputs/Offtake Data Output/20231218_offtake_data_complete.csv',
                                index=False)

## END OF CODE

In [638]:
offtake_data_complete100['month'].unique()

array(['2023-02-01T00:00:00.000000000', '2023-01-01T00:00:00.000000000',
       '2023-03-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [639]:
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-01-01') & (offtake_data_complete100['name of customer'] == '1MG') & (offtake_data_complete100['Division Name'] == 'METABOLICS'), "channel_sales"])

1839937.149999972

In [640]:
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-01-01') & (offtake_data_complete100['name of customer'] == 'NETMEDS') & (offtake_data_complete100['Division Name'] == 'METABOLICS'), "channel_sales"])

605449.7599999991

In [641]:
offtake_data_complete100['name of customer'].unique()

array(['1MG', 'MEDPLUS', 'FLIPKART HEALTH PLUS', 'UDAAN', 'PHARMEASY',
       'NETMEDS', 'WELLNESS', 'APOLLO RETAIL', 'TRUEMEDS', 'ASTER',
       'ZENO HEALTH', 'FRANK ROSS', 'THULASI', 'EASYMEDICO', 'SAVEO'],
      dtype=object)

In [256]:
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-1-01') & (offtake_data_complete100['name of customer'] == 'PHARMEASY'), "channel_sales"])

54387969.40766744

In [642]:
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-1-01') & (offtake_data_complete100['name of customer'] == 'PHARMEASY'), "channel_sales"])

68246425.15506762

In [643]:
sum(offtake_data_complete100.loc[(offtake_data_complete100['month'] == '2023-3-01') & (offtake_data_complete100['name of customer'] == 'PHARMEASY'), "channel_sales"])

40261680.21566686

In [6]:
offtake=pd.read_csv('test_v6.csv')

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (3,4,5,7,12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [7]:
offtake2=pd.read_csv('s3://abt-aa-india-202005001-nonprod/outputs/Offtake Data Output/2022_offtake_data_complete.csv')

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (3,4,5,7,20) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [8]:
offtake2.columns

Index(['month', 'Customer Code', 'pincode', 'Zone',
       'Customer Name (Sold to Party)', 'CFA Name', 'name of customer',
       'SKU No', 'channel_sales', 'ECB_Primary_Sales', 'units_sold', 'PTS',
       'Dostributor Code', 'Division Name', 'Brand Name', 'SKU Name',
       'Affiliate', 'State', 'District', 'Unnamed: 3', 'Unnamed: 4'],
      dtype='object')

In [10]:
offtake2['Merged SKU Code']=''

In [11]:
offtake2=offtake2[['month', 'Customer Code', 'pincode', 'Zone',
       'Customer Name (Sold to Party)', 'CFA Name', 'name of customer',
       'SKU No', 'channel_sales', 'ECB_Primary_Sales', 'units_sold', 'PTS',
       'Merged SKU Code', 'Division Name', 'Brand Name', 'SKU Name',
       'Affiliate', 'State', 'District']]

In [12]:
offtake2['month'] = pd.to_datetime(offtake2['month'])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [14]:
offtake2['month'].unique()

array(['2022-04-01T00:00:00.000000000', '2022-02-01T00:00:00.000000000',
       '2022-01-01T00:00:00.000000000', '2022-06-01T00:00:00.000000000',
       '2022-03-01T00:00:00.000000000', '2022-05-01T00:00:00.000000000',
       '2022-08-01T00:00:00.000000000', '2022-12-01T00:00:00.000000000',
       '2022-10-01T00:00:00.000000000', '2022-07-01T00:00:00.000000000',
       '2022-11-01T00:00:00.000000000', '2022-09-01T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [17]:
one_month_data = offtake2.loc[(offtake2['month'] == '2022-12-01')]

In [18]:
one_month_data['month'].unique()

array(['2022-12-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [19]:
offtake=pd.concat([offtake,one_month_data])

In [20]:
offtake.shape

(2717324, 19)

In [21]:
offtake.columns

Index(['month', 'Customer Code', 'pincode', 'Zone',
       'Customer Name (Sold to Party)', 'CFA Name', 'name of customer',
       'SKU No', 'channel_sales', 'ECB_Primary_Sales', 'units_sold', 'PTS',
       'Merged SKU Code', 'Division Name', 'Brand Name', 'SKU Name',
       'Affiliate', 'State', 'District'],
      dtype='object')

In [22]:
offtake["Affiliate"].unique()

array(['ASC', 'APC', 'AIL', nan, 'Novo', 'Generics'], dtype=object)

In [23]:
offtake_ail= offtake[offtake['Affiliate'].isin(['AIL'])]

In [24]:
offtake_ail.shape

(730824, 19)

In [25]:
offtake_without_ail = offtake[offtake['Affiliate'] != 'AIL']

In [26]:
offtake_without_ail['Affiliate'].unique()

array(['ASC', 'APC', nan, 'Novo', 'Generics'], dtype=object)

In [27]:
offtake_ail['Division Name'].unique()

array(['NEUROLIFE', 'GI PROSPERA', 'METABOLICS', 'GI MAXIMA', 'GI OPTIMA',
       'GENNEXT', 'WH - MITERA', 'CONSUMER CARE', 'WH - FOSTERA',
       'VACCINES', 'GI PRIMA', 'OROCARE', 'GI ADVANCE', 'WH- MITERA',
       'WH FOSTERA'], dtype=object)

In [28]:
offtake_ail['Division Name'] = offtake_ail['Division Name'].replace(['ALLEVIA'],"OROCARE")

offtake_ail['Division Name'] = offtake_ail['Division Name'].replace(['DERMA-COSMETICS'],"DERMA MAGNA")

offtake_ail['Division Name'] = offtake_ail['Division Name'].replace(['WH- MITERA'],"WH - MITERA")

offtake_ail['Division Name'] = offtake_ail['Division Name'].replace(['WH FOSTERA'],"WH - FOSTERA")

offtake_ail['Division Name'] = offtake_ail['Division Name'].replace(['WH- MILIANA'],"WH - MILIANA")

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [29]:
offtake_ail['name of customer'].unique()

array(['1MG', 'MEDPLUS', 'FLIPKART HEALTH PLUS', 'UDAAN', 'PHARMEASY',
       'NETMEDS', 'WELLNESS', 'APOLLO RETAIL', 'TRUEMEDS', 'ASTER',
       'ZENO HEALTH', 'FRANK ROSS', 'THULASI', 'EASYMEDICO',
       'SASTA SUNDAR'], dtype=object)

In [30]:
offtake_ail['name of customer'] = offtake_ail['name of customer'].replace(['SASTA SUNDAR'],"FLIPKART HEALTH PLUS")

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [31]:
ail_pins=pd.read_excel('AIL_pin.xlsx')

In [32]:
ail_pins.shape

(68832, 2)

In [33]:
ail_pins.columns

Index(['Division Name', 'Pincode'], dtype='object')

In [34]:
new_offtake_ail = pd.merge(left=offtake_ail, right=ail_pins, how='left', left_on=['Division Name','pincode'], right_on=['Division Name','Pincode'])

In [35]:
new_offtake_ail.shape

(730824, 20)

In [36]:
New_ail = new_offtake_ail.dropna(subset=['Pincode'])

In [37]:
New_ail.shape

(713802, 20)

In [38]:
New_ail.drop(["Pincode"], axis = 1, inplace = True)

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [39]:
New_ail.shape

(713802, 19)

In [40]:
offtakefull=pd.concat([offtake_without_ail,New_ail])

In [41]:
offtakefull['Affiliate'].unique()

array(['ASC', 'APC', nan, 'Novo', 'Generics', 'AIL'], dtype=object)

In [42]:
offtakefull.to_csv('offtake_for_ail.csv',index=False)